### ISSUE TITLE
Source browse page loads wrong cover images [Bug]

### ISSUE THREAD

**Issue by Farzout** [AriaMoradi/Tachidesk#1000]
Device information
- Suwayomi-Server version: v1.1.1-r1535-win64
- Server Operating System: windows 11 Home
- Server Desktop Environment: N/A
- Server JVM version: Java 8 Update 281 or OpenJDK 8u281
- Client Operating System: <usually the same as above Server Operating System>
- Client Web Browser: microsoft edge
 

Expected behavior
to show the normal image in the browser

Actual behavior
it shows my other thumbnails. for example a naruto thumnail for a jujutsu kaisen manga is shown

Other details
I have moved my download folder which means thumbnail and manga to another folder, would that cause this problem?

**Comment by Robonau** [comment]
1. delete the thumbnails folder in the downloads folder
2. clear the cache in the browser

**Comment by Farzout** [comment]
my problem was fixed clearing my browser cache
