### ISSUE TITLE
[Feature Request] Make entry names updatable

### ISSUE THREAD

**Issue by xdeiimoss** [AriaMoradi/Tachidesk#1002]
## What feature should be added to Suwayomi?
Currently, entry names aren't updatable. If there's any change on the name of the entry on the website itself or something that modifies it in the extension, it doesn't change the name when updating the entry.

##  Why/Project's Benefit/Existing Problem
Some extensions have an option to remove things from the title (example: mangago after the latest update). The changes was made so it gets easier to migrate entries and track entries because it removes things like (Official) from entry names. Currently, those changes aren't working on Suwayomi.

**Comment by Syer10** [comment]
The title does get updated, but only if there manga has no downloads or the downloads rename succeeds.
https://github.com/Suwayomi/Suwayomi-Server/blob/06bfc33e72de3879b3b5da75ada6d98aa0ad18af/server/src/main/kotlin/suwayomi/tachidesk/manga/impl/Manga.kt#L131-L137

**Comment by Syer10** [comment]
Huh, actually, it seems we don't implement title copying inside the SManga, that needs to be fixed https://github.com/Suwayomi/Suwayomi-Server/blob/06bfc33e72de3879b3b5da75ada6d98aa0ad18af/server/src/main/kotlin/eu/kanade/tachiyomi/source/model/SManga.kt#L28

**Comment by aoba-seragakii** [comment]
any updates on this?
