### ISSUE TITLE
[Bug] Changing Java version wiped my data

### ISSUE THREAD

**Issue by Jamato-sUn** [AriaMoradi/Tachidesk#1007]
## Device information
Suwayomi-Server version: v1.1.1 portable for Windows
Server Operating System: Windows 10 x64
Server Desktop Environment: N/A
Server JVM version: Java 8 Update 421
Client Operating System: Windows 10 x64
Client Web Browser: Google Chrome

## Steps to reproduce
1. I grabbed a portable Suwayomi server
2. I installed latest JDK 22 for it to work
3. I added sources and title to my library
4. I was experimenting with Shimeji and at some point installed JRE 8 Update 421 and removed the latest JDK 22

### Expected behavior
No changes in user experience

### Actual behavior
All data from Suwayomi was gone. The repository, the library, sources.
This probably shouldn't happen.

## Other details
There are no other details.

**Comment by Robonau** [comment]
portable ships with its own java, installing any java versions externally wont do anything

**Comment by Jamato-sUn** [comment]
> portable ships with its own java, installing any java versions externally wont do anything

I see. Then the issue is: My data randomly vaporized itself over the course of one night.

**Comment by Robonau** [comment]
where did you extract the portable zip to?

**Comment by Jamato-sUn** [comment]
G:\FilesToKeep\portable_software\Suwayomi-Server-v1.1.1-r1535-windows-x64

**Comment by Robonau** [comment]
and the user has write access to that directory?

**Comment by Jamato-sUn** [comment]
Yes, it's not the system drive. Just my SSD for software.

**Comment by Robonau** [comment]
did u change the "root directory" in the launcher?
cause its not really portable

**Comment by Jamato-sUn** [comment]
Nope. I only added the repo a couple of days back, added a couple of titles to the Library and did... pretty much nothing else.
Yesterday evening the app was working for sure, because I showed it to my friend over Discord. My extensions were there.

**Comment by Robonau** [comment]
yea, the default root directory is in `C:\Users\<Account>\AppData\Local\Tachidesk`
as stated in [the wiki](https://github.com/Suwayomi/Suwayomi-Server/wiki/The-Data-Directory)
you'l need to change it if u want it to be portable

**Comment by Jamato-sUn** [comment]
But I... haven't moved the app anywhere between launches. I'm not like trying to launch it from a new computer or something.

**Comment by Robonau** [comment]
@Syer10 any ideas?

**Comment by Jamato-sUn** [comment]
Oh.... dip. I actually did change Root directory. I checked all the drives and found it elsewhere. And it has all of my stuff. I'm so sorry! I don't know why the software forgot where it was and went to default one, but at least I know where it is now. Please close the issue. =(
