### ISSUE TITLE
[Feature Request] Bulk Migration

### ISSUE THREAD

**Issue by xdeiimoss** [AriaMoradi/Tachidesk#1013]
## What feature should be added to Suwayomi?
add a way to migrate multiple series
it's a feature from TachiJ2K and TachiSY

##  Why/Project's Benefit/Existing Problem
This is a really good feature which makes migrating much easier and faster

**Comment by Robonau** [comment]
this is a client issue not a server issue as migration is entirely done on the client

**Comment by xdeiimoss** [comment]
mb
tyvm for explaining that
will open it in a client instead

**Comment by anikoiau** [comment]
Hi @xdeiimoss were you able to find a client that can perform bulk migrations?
