### ISSUE TITLE
[Bug] Global update only fetches update of a small portion of my library

### ISSUE THREAD

**Issue by sezaru** [AriaMoradi/Tachidesk#1089]
## Device information
- Suwayomi-Server version: v1.1.1-r1535
- Server Operating System: docker
- Server Desktop Environment: N/A
- Server JVM version: The ones that comes from ghcr.io/suwayomi/tachidesk
- Client Operating System: Fedora Silverblue 40
- Client Web Browser: I tried in Chrome and Firefox, but it is clearly not a client issue

## Steps to reproduce
I'm not sure how to reproduce it exactly, but when I was trying to troubleshoot it, I reset the docker volume and imported a backup, and even after that the bug was still there, so I will attach the backup here.

[org.suwayomi.tachidesk_2024-09-22_21-36.zip](https://github.com/user-attachments/files/17091804/org.suwayomi.tachidesk_2024-09-22_21-36.zip)

1. Install the Manganato extension
2. Import the backup
3. Run the global update

### Expected behavior
I expect it to fetch updates from all mangas in my library

### Actual behavior
It only fetches from a small list of mangas (I think around 25% of it)

**Comment by Robonau** [comment]
ive not restored the backup but im guessing its one of a few things
1. u have some of the skip update settings enabled
    `webui > settings > library > global update > skip updating entries > disable all of them`
2. some of the categories are excluded from the global update
    `webui > settings > library > global update > categories > remove all of them from exclude and add them to include`

**Comment by sezaru** [comment]
Thank you, disabling all options in `webui > settings > library > global update > skip updating entries` fixed the issue
