### ISSUE TITLE
Auto download not working

### ISSUE THREAD

**Issue by 24bit192kHz** [AriaMoradi/Tachidesk#1097]
## Device information
Suwayomi-Server version: v1.1.1-r1599

## Steps to reproduce
1. add a weakly manga to library

### Expected behavior
auto download when released

### Actual behavior
doesn't auto download 

## Other details
I left the chapter for 24hrs and it didn't auto download even tho the globalUpdateInterval = 6hrs
I have to go to webui then refresh the manga for the new chapter to apper then it auto download

![image](https://github.com/user-attachments/assets/5ddb9979-5db9-42d3-9fd5-a7466c97da63)

**Comment by Robonau** [comment]
its being excluded from the auto update then, you probably have yr category exclusion setup wrong
`in webui > settings > library settings > Global update > Categories`
if the manga is in a category that i excluded (x) then it will not update

**Comment by Robonau** [comment]
![image](https://github.com/user-attachments/assets/a0a2b2d8-c053-4f25-8029-29523ec88269)
so in my case anything in dropped or finished wont get updated
