### ISSUE TITLE
[Feature Request] Wrong entry count

### ISSUE THREAD

**Issue by aoba-seragakii** [AriaMoradi/Tachidesk#1105]
## What feature should be added to Suwayomi?
The entry count is being displayed incorrectly. It needs to be fixed.

##  Why/Project's Benefit/Existing Problem
It shows a wrong amount of entries and confuses the users.
![image](https://github.com/user-attachments/assets/ddb05745-d0d4-4f20-90c2-188d2c49cf40)

**Comment by kana-shii** [comment]
same as #930
