### ISSUE TITLE
[Bug] Some Extensions do not show up in Source table after Install

### ISSUE THREAD

**Issue by irenfro** [AriaMoradi/Tachidesk#1106]
## Device information
- Suwayomi-Server version: v1.1.1
- Server Operating System: Ubuntu 24.04.1 LTS
- Server Desktop Environment: N/A
- Server JVM version: openjdk version "1.8.0_392"
- Client Operating System: Ubuntu 24.04.1 LTS
- Client Web Browser: Google Chrome Version 130.0.6723.92 (Official Build) (64-bit)

## Steps to reproduce
1. Install Suwayomi-Server in headless mode(using the default WebUI)
  a. I used this part of the [README](https://github.com/Suwayomi/Suwayomi-Server?tab=readme-ov-file#debianubuntu) to install it, followed by the [headless wiki](https://github.com/Suwayomi/Suwayomi-Server/wiki/Configuring-Tachidesk-Server)
2. Add extension-repo to Suwayomi-Server via Keiyoushi's Extensions
3. Install Komga Extension from Browse page on Suwayomi-Server either from Keiyoushi's Extensions or by uploading the apk.  The Komga Version I have been working with is 1.4.58
4. Observe that Komga is now installed in the Extensions Tab on the Browse page.
5. Click on the Sources tab on the Browse Page and observe that Komga does not appear in the Source List

### Expected behavior
Komga should appear in the source list to be searchable as a source

### Actual behavior
Komga is not present in the source list after installing and is not searchable via the global search option

## Other details
1. Debug Logs when installing Komga Extension:
```
Nov 02 12:00:14 manga sudo[18681]: 12:00:14.142 [DefaultDispatcher-worker-10] DEBUG suwayomi.tachidesk.manga.impl.extension.Extension -- Installing eu.kanade.tachiyomi.extension.all.komga
Nov 02 12:00:14 manga sudo[18681]: 12:00:14.150 [OkHttp https://raw.githubusercontent.com/...] DEBUG eu.kanade.tachiyomi.network.NetworkHelper -- --> GET https://raw.githubusercontent.com/keiyoushi/extensions/repo/apk/tachiyomi-all.komga-v1.4.58.apk h2
Nov 02 12:00:14 manga sudo[18681]: 12:00:14.272 [OkHttp https://raw.githubusercontent.com/...] DEBUG eu.kanade.tachiyomi.network.NetworkHelper -- <-- 200 https://raw.githubusercontent.com/keiyoushi/extensions/repo/apk/tachiyomi-all.komga-v1.4.58.apk (122ms, 427323-byte body)
Nov 02 12:00:14 manga sudo[18681]: 12:00:14.291 [DefaultDispatcher-worker-10] DEBUG suwayomi.tachidesk.manga.impl.extension.Extension -- Main class for extension is eu.kanade.tachiyomi.extension.all.komga.KomgaFactory
Nov 02 12:00:14 manga sudo[18681]: 12:00:14.820 [DefaultDispatcher-worker-10] DEBUG suwayomi.tachidesk.manga.impl.util.PackageTools -- loading jar with path: /root/.local/share/Tachidesk/extensions/tachiyomi-all.komga-v1.4.58.jar
Nov 02 12:00:14 manga sudo[18681]: 12:00:14.828 [DefaultDispatcher-worker-10] DEBUG suwayomi.tachidesk.manga.impl.extension.Extension -- Installed source Komga (Komga) (all) with id:4508733312114627536
Nov 02 12:00:14 manga sudo[18681]: 12:00:14.828 [DefaultDispatcher-worker-10] DEBUG suwayomi.tachidesk.manga.impl.extension.Extension -- Installed source Komga (2) (all) with id:8074481155021144106
Nov 02 12:00:14 manga sudo[18681]: 12:00:14.828 [DefaultDispatcher-worker-10] DEBUG suwayomi.tachidesk.manga.impl.extension.Extension -- Installed source Komga (3) (all) with id:5132811728275817394
```
2. The Komga extension is functionable, knowing the id from the server logs above, I can navigate to the source extension and see the expected behavior, i.e. the Komga server contents, `<baseURL>:4567/sources/4508733312114627536`.  However the extension still does not appear in the Source list.  This also means that the connection to the komga server is not the issue as I could navigate to the page and setup the server settings to verify that the content appears.
3. I additionally tried to install a different UI for the server, the VUI based on, and the extension did properly show up in the sources table for that UI, however many of my other extensions did not show up when using that UI version.
4. I noticed that this is not an issue solely to the Komga extension, I tried some of the other extensions provided by Keiyoushi and  they are also not added to the Source Table after being installed, for example an Extension called "Little Garden" also has this same issue it looks like.
5. Photos:
 Extensions Tab:
![image](https://github.com/user-attachments/assets/38545dc4-5410-420b-bbb3-c459dc763445)

 Sources Tab: 
![image](https://github.com/user-attachments/assets/606b7205-3e96-484f-bd88-0a59cdac2ba3)

\<baseURL\>:4567/sources/4508733312114627536
![image](https://github.com/user-attachments/assets/478e83e4-f940-4bea-8f2d-30315b1558a2)

**Comment by Robonau** [comment]
its filtered out by language.
Komga is in "All" not english or local

**Comment by irenfro** [comment]
Thank you!
