### ISSUE TITLE
Manually installed extension doesn't add to source

### ISSUE THREAD

**Issue by MC874** [AriaMoradi/Tachidesk#1110]
**PLEASE READ THIS**

## Device information
- Suwayomi-Server version: v1.1.1-r1689-win64
- Server Operating System: Windows 11 23H2 (OS Build 22631.4317)
- Server Desktop Environment: N/A
- Server JVM version: Bundled with Suwayomi Java 8.0.3920.8
- Client Operating System: Windows 11 23H2 (OS Build 22631.4317)
- Client Web Browser: Bundled Electron and Microsoft Edge 130.0.2849.80

## Steps to reproduce
1. Download APK extension from: https://github.com/keiyoushi/extensions/tree/repo/apk
2. Inside Suwayomi: Browser -> Extensions -> Install external extension (+) -> Open extension (.apk)

### Expected behavior
Extension is installed add added to source

### Actual behavior
Extension is installed but not showing in source & can't be used as source

## Other details
![1](https://github.com/user-attachments/assets/add31957-0fc7-4202-b086-9d993db39301)
![2](https://github.com/user-attachments/assets/48604f4d-aa59-4b42-87d0-21c9e1459788)

**Comment by Robonau** [comment]
its filtered out by language

**Comment by MC874** [comment]
> its filtered out by language

The language is "All", still not showing

**Comment by Robonau** [comment]
"All" is a language, its not all languages

**Comment by MC874** [comment]
> "All" is a language, its not all languages

Now works properly, thanks. It would be good to make it more clear to avoid confusion. And why also it's not showing as "other", is it also a language?
![image](https://github.com/user-attachments/assets/3b6a3cc7-480c-4e5b-8cb5-79cf4eafde05)

**Comment by Robonau** [comment]
other is also a language yes, everything in that filter list is a language.
the language that sources have come from the extensions (the repo).
the defaults being english and local is all we do.

**Comment by MC874** [comment]
> other is also a language yes, everything in that filter list is a language. the language that sources have come from the extensions (the repo). the defaults being english and local is all we do.

Alright, it is confusing at first. But, I have a grasp on it now. Can I turn this into suggestion ticket? Or create a new one?

**Comment by Robonau** [comment]
make a new one, you probably want to make it in the webui repo not the server one since thats what has the defaults

**Comment by MC874** [comment]
> make a new one, you probably want to make it in the webui repo not the server one since thats what has the defaults

Alright thank you, I'll close this now.
