### ISSUE TITLE
[Bug] Wrong thumbnail after restoring backup

### ISSUE THREAD

**Issue by aoba-seragakii** [AriaMoradi/Tachidesk#1111]
## Device information
- Suwayomi-Server version: v1.1.1-r1600
- Server Operating System: Windows 11
- Server Desktop Environment: N/A
- Server JVM version: Java 8
- Client Operating System: Windows 11
- Client Web Browser: Opera

## Steps to reproduce
1. Restore backup from mihon or fork (in my case, restored from a TachiSY fork
2. Check some thumbnails

### Expected behavior
The thumbnails should be correct

### Actual behavior
Thumbnails are actually messed up (some of them), even though in the fork I'm using they are being displayed correctly
It's getting thumbnails from other manga in the library

## Other details
Thumbnail in suwayomi
![image](https://github.com/user-attachments/assets/c9876ace-0cc0-48c6-8268-b53da87c5501)

actual thumbnail
![image](https://github.com/user-attachments/assets/5ab220b0-b037-4a6d-8bc0-c5e105c94b5f)

**Comment by Robonau** [comment]
delete the thumbnails folder (in the data/downloads folder)
and
clear browser cache

**Comment by aoba-seragakii** [comment]
> delete the thumbnails folder (in the data/downloads folder) and clear browser cache

I did that and it didn't work...

**Comment by Robonau** [comment]
that's all the places those images are stored.
