### ISSUE TITLE
[Feature Request] search by chapter name

### ISSUE THREAD

**Issue by xdeiimoss** [AriaMoradi/Tachidesk#1159]
## What feature should be added to Suwayomi?
Add searching by chapter name
it would be kind of a niche feature but it would be really good in my opinion
Depending if the manga you're reading is an anthology, the chapters usually have different names based on the name of the one-shot, so sometimes a user forgets the name of the anthology itself but remembers the name of the oneshot, a feature like this would help a lot

**Comment by Robonau** [comment]
this is a UI issue, move to webui repo

**Comment by xdeiimoss** [comment]
I thought it would be a server issue as I mean searching on the library and not on the entry itself...

**Comment by Robonau** [comment]
its a UI thing

**Comment by xdeiimoss** [comment]
Will be closing and moving to webui instead then
tyvm
