### ISSUE TITLE
[Feature Request] save some stuff on database instead

### ISSUE THREAD

**Issue by xdeiimoss** [AriaMoradi/Tachidesk#1200]
## What feature should be added to Suwayomi?
Appearance configs (theme, manga item width)
Browse configs (source and extension allowed languages)
Both of them should be saved under the database instead of cache (at least I assume it is under cache because when I clear the cache in my browser, all of those options resets to default)
Basically, all of those should be saved somewhere that it wouldn't be affected if the cache is cleared

**Comment by Robonau** [comment]
this is a UI issue not a server issue

**Comment by xdeiimoss** [comment]
will create the issue under webui then
ty
