### ISSUE TITLE
[Bug] cubari doesn't work

### ISSUE THREAD

**Issue by xdeiimoss** [AriaMoradi/Tachidesk#1201]
## Device information
- Suwayomi-Server version: v1.1.1-r1650
- Server Operating System: Windows11
- Server Desktop Environment: N/A
- Server JVM version: Java 21
- Client Operating System: Windows 11
- Client Web Browser: Opera

## Steps to reproduce
1. try to search for cubari gist

### Expected behavior
it should work

### Actual behavior
gives error Unable to load data
Stub!

**Comment by Robonau** [comment]
can you add a screenshot or more information.
`try to search for cubari gist` means absolutely nothing to me

**Comment by xdeiimoss** [comment]
cubari works by searching stuff like this in the extension:
cubari:gist/Z2lzdC9mdW5reWhpcHBvLzFkNDBiZDVkYWUxMWUwM2E2YWYyMGU1YTlhMDMwZDgxL3Jhdy9vcG0uanNvbg
it would give out this https://cubari.moe/read/gist/Z2lzdC9mdW5reWhpcHBvLzFkNDBiZDVkYWUxMWUwM2E2YWYyMGU1YTlhMDMwZDgxL3Jhdy9vcG0uanNvbg/
screenshot of error
![image](https://github.com/user-attachments/assets/04a2282a-e0a7-425c-b8e7-9d56611bb6f9)

**Comment by schroda** [comment]
see #161

**Comment by Robonau** [comment]
works as intended now![Image](https://github.com/user-attachments/assets/be972669-72c6-4a83-80ff-07141fd61dc8)
