### ISSUE TITLE
[Bug] MangaGeko broken images

### ISSUE THREAD

**Issue by Rouruki** [AriaMoradi/Tachidesk#1202]
## Device information
- Suwayomi-Server version: (Example: v1.1.1-r1535-win32)
- Server Operating System: (Example: Ubuntu 20.04)
- Server Desktop Environment: N/A or (Example: Gnome 40)
- Server JVM version: bundled with win32 or (Example: Java 8 Update 281 or OpenJDK 8u281)
- Client Operating System: <usually the same as above Server Operating System>
- Client Web Browser: (Example: Google Chrome 89.0.4389.82) 

## Steps to reproduce
1. Extension only shows broken images
2. Main Site is fully functional and shows images

### Expected behavior
![image](https://github.com/user-attachments/assets/f020ee7e-9c6c-425e-9f51-09865abc7d86)
![image](https://github.com/user-attachments/assets/216f71f3-cb7a-40d6-a031-115300ce6bcc)
![image](https://github.com/user-attachments/assets/f9640c79-d401-478f-b3cc-13eeae39619e)

### Actual behavior
![image](https://github.com/user-attachments/assets/89c5abfb-7618-4098-951c-87ac00c19b0d)
![image](https://github.com/user-attachments/assets/fcf528e3-6e2c-4cff-aafe-f9be0ddd9dec)
![image](https://github.com/user-attachments/assets/257d7e39-8747-4441-887c-c6408482c78c)

**Comment by Robonau** [comment]
this is likely an extension issue rather than a Suwayomi issue.
check it it works on mihon if possible, if it doesn't then make an issue in whatever extension repo you are using

**Comment by Rouruki** [comment]
> this is likely an extension issue rather than a Suwayomi issue. check it it works on mihon if possible, if it doesn't then make an issue in whatever extension repo you are using

Even in mihon, it also shows broken images.

**Comment by Robonau** [comment]
then its an extension issue and not a suwayomi issue
take it up with whatever extension repo you are using
