### ISSUE TITLE
[Bug] <error value.toString is not a function, when launched the app, because of kaspersky>

### ISSUE THREAD

**Issue by PHBN1964** [AriaMoradi/Tachidesk#1214]
## Device information
- Suwayomi-Server version: v1.1.1-r1535-win64
- Server Operating System: win64
- Server Desktop Environment: N/A 
- Server JVM version: OpenJDK 8u281
- Client Operating System: win64
- Client Web Browser:Google Chrome 89.0.4389.82 

## Steps to reproduce
1. activate kaspersky
2. launch the app

### Expected behavior
for the app to work normally with the kaspersky active

### Actual behavior
it says that launched it only appear the value.toString is not a function, when he kaspersky is active

## Other details
i already tried to exclude and to put trust on the program in the kaspersky, but it didn't work, it only works when turn off

**Comment by Robonau** [comment]
this is a webui issue not a server issue

**Comment by Syer10** [comment]
Library issue https://github.com/apollographql/apollo-client/issues/12202
