### ISSUE TITLE
[Bug] ManaToki configuration

### ISSUE THREAD

**Issue by Rawtuna101** [AriaMoradi/Tachidesk#202]
## Device information
- Tachidesk version: v0.5.1 docker
- Server Operating System: Ubuntu 20.04
- Server Desktop Environment: Ubuntu server
- Server JVM version: docker version
- Client Operating System: Ubuntu 20.04 Mate i3wm
- Client Web Browser: Firefox 92.0

## Steps to reproduce
1. ManaToki (KO) shows nothing.
2. To change a url, click the configuration button.

### Expected behavior
There should be settings to change

### Actual behavior
Configuration page doesn't have any content

![스크린샷 2021-09-19 11-21-26](https://user-images.githubusercontent.com/53120647/133913434-baf6ea03-0663-43e9-9c56-3afa7ac240d7.png)

## Other details
+similar source NewToki's configuration works but even after changing a url, images still can't be loaded

I'm not that good at english, so there can be weird word usages. Thanks

**Comment by AriaMoradi** [comment]
Use the latest preview for a fix.
I tried using NewToki (with `BaseUrl = https://newtoki106.com`) and It worked, probably you are getting IP banned, try with a VPN?
