### ISSUE TITLE
[Feature Request] Portable version?

### ISSUE THREAD

**Issue by MagicalDrizzle** [AriaMoradi/Tachidesk#207]
---

## What feature should be added to Tachidesk?
Portable support.

##  Why/Project's Benefit/Existing Problem
Allows you to bring your library and settings with you anywhere.

I have tried manually setting %localappdata% before launching tachidesk, yet it still stores its configs in localappdata?
```
set "LOCALAPPDATA=%CD%"
jre\bin\java -Dsuwayomi.tachidesk.config.server.debugLogsEnabled=true -jar  Tachidesk.jar
```

**Comment by Syer10** [comment]
Using `-Dsuwayomi.tachidesk.config.server.rootDir=` should work

**Comment by MagicalDrizzle** [comment]
seems to work, thank you!
