### ISSUE TITLE
[Feature Request] Ability to search from multiple sources

### ISSUE THREAD

**Issue by syedaliasad649** [AriaMoradi/Tachidesk#209]
## What feature should be added to Tachidesk?
Ability to search from multiple sources at the same time using the source menu. (Bonus request: it showing the latest chapter in a small window near the results)

##  Why/Project's Benefit/Existing Problem
This will allow the efficient utilization of using multiple sources and will lessen the hassle of going through all the sources to find the one which has the latest chapter.

**Comment by AriaMoradi** [comment]
This feature should be handled in clients, WebUI supports it now.
