### ISSUE TITLE
[Bug] Updates not showing up properly

### ISSUE THREAD

**Issue by syedaliasad649** [AriaMoradi/Tachidesk#214]
The following bug was found in the stable tachidesk ver- 'Tachidesk-Server-v0.5.3-r966-linux-x64'
## Steps to reproduce
1. Run Tachidesk
2. Go to updates

### Expected behavior
Automatically showing the updates. 

### Actual behavior
Not showing updates until a comic (or Item in library) is opened.

## Other details
Issue might be solved by creating a script that scans through the list of library items and checks for chapters automatically or after pressing a button.

**Comment by AriaMoradi** [comment]
That's how it works now, not an issue.

**Comment by AriaMoradi** [comment]
That's how it works now, not an issue.

**Comment by AriaMoradi** [comment]
The behavior will be changed in future updates.
