### ISSUE TITLE
[Feature Request] The feasability of supporting Lnreader extensions (LNReader/lnreader)

### ISSUE THREAD

**Issue by frykauf** [AriaMoradi/Tachidesk#215]
Currently, many LN sites are adding cloudflare hCaptcha, now including novel-updates. 
(Basically Mangadex+Mangaupdates for novels)

That essentially broke EPUB creation for novels on desktop. And some sites don’t even work in FIrefox’s "reader mode“.
Both meaning that if a novel is less „popular“, even scrapers websites won’t scrape it/keep it updated for new chapters.

But on mobile, LNReader/lnreader is the defacto Tachyiomi clone for LNs/WNs/etc. . So even if some site breaks, the community responds quickly, similarly to Tachyiomi community to fix the issue.

So my question: „How feasable would it be to support "LNReader / lnreader“ sources?“

I’m not even asking about making a reader that support text. Something that can reliably make individual .txt chapter files & complete epub, to predefined folder & could follow and update (add chapters/update existing chapters if updated) would be preferable.

Lnreader can be found on github as LNReader / lnreader.
I don’t think this is a duplicate feature request as it’s adapting extensions that work somewhat similarly to Tachidesk/Tachyiomi but for Novels, without developing these extensions from ground up/keeping them updated&working.

And since Tachidesk supports Aniyomi extensions, I though I gave it a shot & ask.

**Comment by AriaMoradi** [comment]
Just
No.
Supporting Aniyomi features was already a nightmare.
Maybe in another life...

ps: Anyone can fork Tachidesk and do whatever they want. Be the change you want to see in the world.
