### ISSUE TITLE
[Feature Request] Ability to change the download location

### ISSUE THREAD

**Issue by rafael-fb** [AriaMoradi/Tachidesk#221]
## What feature should be added to Tachidesk?
Ability to change the download location in the settings menu so we can choose a specific folder to store the downloaded chapters. (Currently, they are stored by default at 'User\AppData\Local\Tachidesk\manga')

##  Why/Project's Benefit/Existing Problem
This will be extremely useful for people who like to have chapters synced using cloud services like OneDrive, so we can easily access the chapters on the phone, iPad, another PC, and so on (devices that don't run Tachiyomi)... As it is now, I have to move new chapters from the 'Tachidesk\manga' folder to my synced OneDrive folder every time I download new chapters (and that is super annoying).

**Comment by AriaMoradi** [comment]
You can change the data root directly, it will also move your downloads directly with it.

Refer to this wiki page for more info: https://github.com/Suwayomi/Tachidesk-Server/wiki/Configuring-Tachidesk-Server

**Comment by Ashish-Bakshi** [comment]
i am trying to delete a folder of manga from my local folder of tachidesk but i cant delete it because it says the folder is open in another app even though i have closed the app.  please help

**Comment by Robonau** [comment]
> i am trying to delete a folder of manga from my local folder of tachidesk but i cant delete it because it says the folder is open in another app even though i have closed the app. please help

don't try to commandeer a completely different issue
