### ISSUE TITLE
[Feature Request] Library Update Option

### ISSUE THREAD

**Issue by Sehraan** [AriaMoradi/Tachidesk#234]
## What feature should be added to Tachidesk?
Library update option.

##  Why/Project's Benefit/Existing Problem
Library update option needs to be added because it will help the user to get new chapters easily and fast. Currently in Tachidesk, to update a manga we have to go open the manga in library section and reload the page or wait to get new chapter because it doesn't show updates until a comic (or Item in library) is opened so you have to go to all the manga in library to know if there is a new chapter released for that manga.

**Comment by AriaMoradi** [comment]
This feature is planned for the next release.

**Comment by Sehraan** [comment]
on preview or stable version of Tachidesk. @AriaMoradi

**Comment by AriaMoradi** [comment]
I think it's not implemented yet, you can track the work on our discord, and help here and there if you are interested.

**Comment by Sehraan** [comment]
@AriaMoradi i am already a member of your discord server.
Is your username on discord armor

**Comment by AriaMoradi** [comment]
> @AriaMoradi i am already a member of your discord server. Is your username on discord armor

yes
