### ISSUE TITLE
[Feature Request] Ability to change the browser tachidesk launches on.

### ISSUE THREAD

**Issue by syedaliasad649** [AriaMoradi/Tachidesk#238]
## What feature should be added to Tachidesk?
A prompt or setting that allows you to change the browser tachidesk gets launched on.

##  Why/Project's Benefit/Existing Problem
Will help improve the customizability of the app.

**Comment by ff2400t** [comment]
For nowTachiDesk opens in your Default browser set in the system settings. You can change that if you want. If you don't want to use the default browser you can open the url in the browser of your choice after the initial launch.

**Comment by syedaliasad649** [comment]
> 
> 
> you can open the url in the browser of your choice after the initial launch.

ooh, thnx !
Still I think it would be a neat little feature to have a prompt that lets you change the Tachiyomi default instead of compromising on the system default.
