### ISSUE TITLE
[Feature Request] Unraid Community App

### ISSUE THREAD

**Issue by Kpalaz** [AriaMoradi/Tachidesk#239]
---

## What feature should be added to Tachidesk?
Adding a community app for Unraid so that less experienced docker users can use the app. ([guide for this](https://forums.unraid.net/topic/57181-docker-faq/#comment-566084))

##  Why/Project's Benefit/Existing Problem
Unraid has a large userbase that nearly exclusively use the community apps to avoid directly dealing with docker, having tachidesk there will increase the visibility of the app.

**Comment by jsavargas** [comment]
> ## What feature should be added to Tachidesk?
> Adding a community app for Unraid so that less experienced docker users can use the app. ([guide for this](https://forums.unraid.net/topic/57181-docker-faq/#comment-566084))
> 
> ## Why/Project's Benefit/Existing Problem
> Unraid has a large userbase that nearly exclusively use the community apps to avoid directly dealing with docker, having tachidesk there will increase the visibility of the app.

![image](https://user-images.githubusercontent.com/6886410/140171552-a52b3a9e-5155-425e-829f-8e320986809d.png)

**Comment by Kpalaz** [comment]
> > ## What feature should be added to Tachidesk?
> > Adding a community app for Unraid so that less experienced docker users can use the app. ([guide for this](https://forums.unraid.net/topic/57181-docker-faq/#comment-566084))
> > ## Why/Project's Benefit/Existing Problem
> > Unraid has a large userbase that nearly exclusively use the community apps to avoid directly dealing with docker, having tachidesk there will increase the visibility of the app.
> 
> ![image](https://user-images.githubusercontent.com/6886410/140171552-a52b3a9e-5155-425e-829f-8e320986809d.png)

appreciate it
