### ISSUE TITLE
[Feature Request]Add basic authentication to Tachidesk extension(v1.2.3)

### ISSUE THREAD

**Issue by varoOP** [AriaMoradi/Tachidesk#247]
Currently if the Tachidesk server has basic authentication set up, there is no way for the extension to access it.
Only get a HTTP 401 error even with the username and password added to the URL.

It would be great if the Tachidesk extension of Tachiyomi could accept basic auth credentials in it's setting and use them to authenticate.

Opened the issue on the Tachiyomi repo over here:https://github.com/tachiyomiorg/tachiyomi-extensions/issues/9776

---

##  Project's benefit
It would make it possible for users to access their Tachidesk-server from the Tachidesk extension of Tachiyomi even if the server has basic authentication switched on.

**Comment by JiPaix** [comment]
@varoOP tachiyomiorg/tachiyomi-extensions#11477 has been merged.  
this issue can be closed now.

**Comment by AriaMoradi** [comment]
Thanks for the contribution!
