### ISSUE TITLE
Rewrite Download Queue

### ISSUE THREAD

**Issue by AriaMoradi** [AriaMoradi/Tachidesk#262]
- Testable design
- support operations
    - enqueue
    - unqueue
    - pause/stop
    - re-order
- use corutines
- parallel image downloading and smooth percentage
- parallel download jobs
- status websocket

**Comment by thisisnaveen** [comment]
unqueue is not working properly in WebUI on a recent stable release.

**Comment by thisisnaveen** [comment]
re-ordering the downloads also not working properly. Can't give download priority due to this

**Comment by chiyorocks** [comment]
Just curious, but will this be implemented alongside #157?

**Comment by AriaMoradi** [comment]
> Just curious, but will this be implemented alongside #157?

This is a pre-requisite of #157 , auto-download should be a function of clients, I think.

**Comment by hwwilliams** [comment]
> > Just curious, but will this be implemented alongside #157?
> 
> This is a pre-requisite of #157 , auto-download should be a function of clients, I think.

Will the auto-download functionality be included in the web UI as well since it is also a client?

**Comment by Robonau** [comment]
> Will the auto-download functionality be included in the web UI as well since it is also a client?

if someone implements the feature then yes
if no one does then no
