### ISSUE TITLE
[Bug] extension MangaRaw (manga1000) is not working

### ISSUE THREAD

**Issue by tangorcraft** [AriaMoradi/Tachidesk#276]
## Device information
- Tachidesk version: v0.6.0-r1048-windows-x64
- Server Operating System: Windows 7 64bit
- Server Desktop Environment: N/A
- Server JVM version: bundled with tachidesk win64
- Client Operating System: Windows 7 64bit
- Client Web Browser: Vivaldi 3.7.2218.45, also tried bundled Electron

## Steps to reproduce
1. Install MangaRaw extension
2. Browse MangaRaw from sources

### Expected behavior
List or manga is shown

### Actual behavior
Loading circle is spinning forever

## Other details
Opening search, browse or latest I only see spinning circle and nothing happens no matter how long I wait.
Extension does work inside Tachiyomi as intended.

**Comment by tangorcraft** [comment]
After some debugging I got error "javax.net.ssl.SSLHandshakeException: Received fatal alert : protocol_version", looking further I found that MangaRaw site was rejecting TLSv1.2, opening site in browser showed that it works on TLSv1.3
adding command like option `-Djdk.tls.client.protocols=TLSv1,TLSv1.1,TLSv1.2,TLSv1.3` to the bat file solved the problem

**Comment by Syer10** [comment]
What extension/language are you referring to, the Japanese MangaRaw extension does not contain a MangaRaw source

**Comment by AriaMoradi** [comment]
Stale issue
