### ISSUE TITLE
[Feature Request] Adding DEB package releases to the Github Releases

### ISSUE THREAD

**Issue by hiddeninthesand** [AriaMoradi/Tachidesk#278]
## What feature should be added to Tachidesk?
Not so much a feature added to Tachidesk, but to this repo. As the title says, adding the DEB packages from the already maintained Launchpad PPA to the stable binary releases on this repo.

##  Why/Project's Benefit/Existing Problem
Would make it significantly easier to put it on the [MPR.](https://mpr.hunterwittenborn.com/)

**Comment by AriaMoradi** [comment]
@mahor1221

**Comment by AriaMoradi** [comment]
That repo awfully looks like the AUR, maybe all you need is porting https://aur.archlinux.org/packages/tachidesk

**Comment by hiddeninthesand** [comment]
Using the deb package lets me keep direct compatibility with the official Debian repository. The change is also for the sake of completeness, as it's strange that there's official Debian packages but it's not released on the Github.

**Comment by mahor1221** [comment]
Here you go: https://mpr.hunterwittenborn.com/packages/tachidesk
I've already had considered MPR but I heard it has some problems? 
Tell me on discord or MPR if it doesn't work as you expected

Should I make a PR to build the deb package in `publish.yml` and `push_build.yml` workflows? @AriaMoradi

**Comment by AriaMoradi** [comment]
> Should I make a PR to build the deb package in publish.yml and push_build.yml workflows?

sure?
