### ISSUE TITLE
[Feature Request] Change local source folder location

### ISSUE THREAD

**Issue by 123321mario** [AriaMoradi/Tachidesk#280]
## What feature should be added to Tachidesk?
Setting to change local source folder location for something else than %appdata%\..\Local\Tachidesk\local

##  Why/Project's Benefit/Existing Problem
Not everyone wants to move their stuff on a somewhat hidden folder in the C:\ drive, my manga stuff is stored on a NAS outside my PC.

**Comment by thisisnaveen** [comment]
I also would like to suggest that.

**Comment by AUKUMA** [comment]
I also would like to suggest that.

**Comment by github-account1111** [comment]
This is crucial.
Perhaps also consider letting the user open the books directly from inside File Explorer via the "Open with" menu.

A workaround is creating a symlink in the local source folder to wherever your actual files are stored.
From elevated Powershell (replace the parts inside `<>`):
```powershell
 New-Item -ItemType SymbolicLink -Path "$Env:LOCALAPPDATA\Tachidesk\local\<my-books>" -Target "<path/to/my-books>"
```

Edit: Or if you want to respect the [folder structure](https://github.com/Suwayomi/Tachidesk-Server/wiki/Local-Source#folder-structure) then you could run this instead to avoid creating an extra root folder:
```powershell
Get-ChildItem -LiteralPath "<path/to/my-books>" | ForEach-Object {New-Item -ItemType SymbolicLink -Path "$Env:LOCALAPPDATA\Tachidesk\local\$($_.Name)" -Target "$($_.FullName)"}
```

**Comment by campana-giuseppe** [comment]
I would add, on server it may not be good to have only one folder as source and you might need more folders to organise the resources, having the possibility to add more local sources. It would be feasible and not too much complicated to implement multiple local source (even inside the folder local)? Or there is a workaround for it?

**Comment by AriaMoradi** [comment]
> I would add, on server it may not be good to have only one folder as source and you might need more folders to organise the resources, having the possibility to add more local sources. It would be feasible and not too much complicated to implement multiple local source (even inside the folder local)? Or there is a workaround for it?

Open a new issue for this.

**Comment by minhngoc25a** [comment]
Unfortunately, Tachidesk doesn't work well with symbolic links. Trying to do so will cause the web UI to be blank when browsed. Editing the startup arguments ourselves might be the only way to change this, but it's still a wrong decision to implement the custom data directory there.

**Comment by AriaMoradi** [comment]
> Unfortunately, Tachidesk doesn't work well with symbolic links.

Try using hard links, soft links on windows are not really path links. 

 > Editing the startup arguments ourselves might be the only way to change this, but it's still a wrong decision to implement the custom data directory there.

Do you have a proposal on what our alternatives are if we want to do it better?

**Comment by minhngoc25a** [comment]
Yes, maybe you can use an environment variable to set the custom directory for Tachidesk. I think it will be easier to implement than adding an option in the GUI alone.

**Comment by minhngoc25a** [comment]
> Try using hard links, soft links on windows are not really path links.

Hard links have ever only been available for files, not directories.

**Comment by AriaMoradi** [comment]
> > Try using hard links, soft links on windows are not really path links.
> 
> Hard links have ever only been available for files, not directories.

Sorry, Junction was what I meant.

**Comment by minhngoc25a** [comment]
> > > Try using hard links, soft links on windows are not really path links.
> > 
> > 
> > Hard links have ever only been available for files, not directories.
> 
> Sorry, Junction was what I meant.

None of the options in the command `mslink` work. And Junction is one of them.

**Comment by Syer10** [comment]
Added to the preview recently.
