### ISSUE TITLE
[Bug] chapters load forever on JAPSCAN

### ISSUE THREAD

**Issue by FA-TAAA** [AriaMoradi/Tachidesk#285]
## Device information
- Tachidesk version: v0.6.0 + WebUI: r893
- Server Operating System: Windows 10 19044.1415
- Server Desktop Environment: N/A 
- Server JVM version: build 1.8.0_311-b11
- Client Operating System: Windows 10 19044.1415
- Client Web Browser: Brave 1.34.80

## Steps to reproduce
1. Type Manga on Japscan
2. Click on the Chapter

### Expected behavior
Show me the manga panels

### Actual behavior
Loading animation , forever

## Other details
I tried the same manga on the same extension in Tachiyomi on Android and it worked , on pc i tried with all the bat files and it keeps loading forever

**Comment by AriaMoradi** [comment]
Japscan is not supported. refer to #161

**Comment by FA-TAAA** [comment]
> Japscan is not supported. refer to #161

Thanks for responding 
Can i know the reason please ?
