### ISSUE TITLE
[Feature Request] Support Extension Lib 1.3

### ISSUE THREAD

**Issue by Syer10** [AriaMoradi/Tachidesk#296]
## What feature should be added to Tachidesk?
Extensions lib v1.3 was released recently, extensions have not started using it yet but I feel Tachidesk should implement it before they do.
https://github.com/tachiyomiorg/extensions-lib

##  Why/Project's Benefit/Existing Problem
Support for Extensions lib v1.3 will allow easy upgrade when the extensions update to the next version

**Comment by AriaMoradi** [comment]
closed in #316
