### ISSUE TITLE
[Feature Request] Add linux-all.tar.gz

### ISSUE THREAD

**Issue by mahor1221** [AriaMoradi/Tachidesk#302]
## What feature should be added to Tachidesk?
Consider adding `Tachidesk-Server-v<ver>-r<rev num>-linux-all.tar.gz` that contains:
```
tachidesk-server-browser-launcher.sh
tachidesk-server-debug-launcher.sh
tachidesk-server-electron-launcher.sh
tachidesk-server.desktop
tachidesk-server.png
tachidesk-server.jar
```
And remove `Tachidesk-Server-v<ver>-r<rev num>-linux-x64.tar.gz` If it's not needed?

##  Why/Project's Benefit/Existing Problem
It makes doing universal changes to AUR, MPR, PPA and other possible future packages ( NixPkg and RPM ) a lot easier.

**Comment by mahor1221** [comment]
I can add it if you want

**Comment by AriaMoradi** [comment]
Making a flatpak for universal distro support is better

We could very much do your proposal but the scripts need to be changed a bit and check for java/electron executable availablity

**Comment by mahor1221** [comment]
I didn't mean to say using it as way of supporting a lot of distros. It's like a replacement for plain `Tachidesk-Server-*.jar` in release section so I can make AUR, MPR and PPA more automated and put less time on updating them. Also the compressed tar.gz file is about 10% smaller.

Electron launcher script checks for electron availability in AUR and various deb packages so it's not like we are not doing it already.

**Comment by AriaMoradi** [comment]
`Tachidesk-Server-v<ver>-r<rev num>-linux-all.tar.gz` means any cpu architecture(in our naming scheme) and it could potentially support any distro, why not have it?

> so I can make AUR, MPR and PPA more automated and put less time on updating them

Why don't you make CI scripts for automatic updating? I had the idea for the `tachidesk-preview` AUR package and even made an account ArMor007Bot for automation

**Comment by mahor1221** [comment]
> Tachidesk-Server-v<ver>-r<rev num>-linux-all.tar.gz means any cpu architecture(in our naming scheme) and it could potentially support any distro, why not have it?

Could you clarify a little I wasn't able to understand completely. Does "it" refer to `Flatpack`? If it does then Yeah sure I think me or somebody else can make a Flatpack someday. but it's not related to my request.

> Why don't you make CI scripts for automatic updating? I had the idea for the tachidesk-preview AUR package and even made an account ArMor007Bot for automation

That's really cool I'll definitely check how did you do it 👍. but the bot and the tar.gz file can coexist.

I've deployed the Idea in [Tachidesk-Sorayomi](https://github.com/Suwayomi/Tachidesk-Sorayomi/releases). Icon and desktop file are included in the tar.gz archive. Its icon has changed today and the [AUR package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=tachidesk-sorayomi-bin)'s icon changed too without manual intervention. In the case of Tachidesk-Server where I have to update the package across four different platforms manually a tar.gz archive has a lot more value and this is not something I can do with a bot easily.

**Comment by AriaMoradi** [comment]
That can work, make a PR
