### ISSUE TITLE
[Feature Request] Filter updates by category

### ISSUE THREAD

**Issue by alkumaish** [AriaMoradi/Tachidesk#310]
## What feature should be added to Tachidesk?
Add the ability to filter updates (tab/section) by category and have that filter saved and applied every time updates are checked.

##  Why/Project's Benefit/Existing Problem
This will allow the us to see the updates for the series that we are currently/actively following.   For example I have categories like "Current", "To-Read", "Hiatus", "finished" and "Dropped".
Anyone using Tachidesk to read more few comics will love this.

**Comment by Syer10** [comment]
Completed
