### ISSUE TITLE
[Feature Request] Meta key to store data on server level

### ISSUE THREAD

**Issue by DattatreyaReddy** [AriaMoradi/Tachidesk#312]
## What feature should be added to Tachidesk?
- Now, Meta key ({baseURL}/api/v1/manga/{mangaId}/meta) is supported for Manga and Chapters.
- Need this Meta key on server level (something like ({baseURL}/api/v1/meta)).
- Need this Meta key on Category level (something like ({baseURL}/api/v1/meta)).

##  Why/Project's Benefit/Existing Problem
- Can sync client settings across apps 
  - Why: To sync app settings of Soroyomi across different apps like Android, Windows, Web,
- Apply manga filter on a category level.

**Comment by Robonau** [comment]
i would also like meta for sources, for favorited sources
this would likely be cross UI (same data would be used by multiple UIs (webUi JUI Sora etc))
and not just cross platform using the same UI
