### ISSUE TITLE
[Bug] Ubuntu PPA missing

### ISSUE THREAD

**Issue by maanisim** [AriaMoradi/Tachidesk#318]
This bug was open in order to track as to when PPA will work again (https://github.com/Suwayomi/Tachidesk-Server#ubuntu)

## Device information
- Tachidesk version: All
- Server Operating System: Ubuntu 20.04
- Server Desktop Environment: N/A
- Server JVM version: N/A
- Client Operating System: Ubuntu 20.04
- Client Web Browser: N/A

## Steps to reproduce
```
sudo add-apt-repository ppa:suwayomi/tachidesk-server
sudo apt update
sudo apt install tachidesk-server
```

### Expected behavior
Successful Installation of the repository.

### Actual behavior
```
ubuntu@pc:~$ sudo add-apt-repository ppa:suwayomi/tachidesk-server
[sudo] password for ubuntu: 
Cannot add PPA: 'ppa:~suwayomi/ubuntu/tachidesk-server'.
The team named '~suwayomi' has no PPA named 'ubuntu/tachidesk-server'
Please choose from the following available PPAs:
 * 'tachidesk':  Tachidesk
```

**Comment by AriaMoradi** [comment]
Download DEB package from release section or Install from the MPR for the time being. The PPA will be fixed soon.

**Comment by mahor1221** [comment]
PPA is now usable again: https://launchpad.net/~suwayomi/+archive/ubuntu/tachidesk-server

**Comment by maanisim** [comment]
Can confirm, it now appears to be successfully working.
