### ISSUE TITLE
[Feature Request] search through all extensions  

### ISSUE THREAD

**Issue by belovist** [AriaMoradi/Tachidesk#321]
## What feature should be added to Tachidesk?
when i search through  sources then i have to search one by one in every extensions 

##  Why/Project's Benefit/Existing Problem
it will help us look through every extensions easily without going though each an every one

**Comment by DattatreyaReddy** [comment]
Hi @vineet05, Global search is a feature that need to be implemented on client side. 
Tachidesk-web have already implemented it and it will be available for release (it's available in preview i think).
Also, [Tachidesk-Sorayomi](https://github.com/Suwayomi/Tachidesk-Sorayomi) supports Global search now.

**Comment by DattatreyaReddy** [comment]
Also, copy of this issue has already been closed. 
[#209](https://github.com/Suwayomi/Tachidesk-Server/issues/209)
