### ISSUE TITLE
[Bug] Extension WebtoonXYZ is not working

### ISSUE THREAD

**Issue by onmyouji** [AriaMoradi/Tachidesk#323]
## Device information
- Tachidesk version: v0.6.2-r1074-windows-x64
- Server Operating System: Windows 10 64-bit
- Server Desktop Environment: N/A 
- Server JVM version: bundled with tachidesk win64 
- Client Operating System: Windows 10 64-bit
- Client Web Browser: bundled Electron (I also try using Firefox 98.0.2)

## Steps to reproduce
1. Install WebtoonXYZ extension
2. Go to Sources
3. Click 'Latest' or 'Browse'

### Expected behavior
It should display the list of manga.

### Actual behavior
Spinning loading circle, no manga displayed.

## Other details
Extension does work inside Tachiyomi without any problem.

**Comment by onmyouji** [comment]
Attached is the output from the debug launcher

[debug.txt](https://github.com/Suwayomi/Tachidesk-Server/files/8344846/debug.txt)

**Comment by Syer10** [comment]
Cloudflare is blocking Tachidesk-Server, nothing we can really do about it
