### ISSUE TITLE
[Bug] ReadComicOnline extension loads infinitely

### ISSUE THREAD

**Issue by popcar2** [AriaMoradi/Tachidesk#324]
## Device information
- Tachidesk version: v0.62
- Server Operating System: Windows 10
- Server Desktop Environment: N/A
- Server JVM version: bundled with win32
- Client Operating System: Windows 10
- Client Web Browser: Firefox 98.0.2

## Steps to reproduce
1. Install ReadComicOnline extension
2. Attempt to browse or read a comic hosted there

### Expected behavior
I should be able to browse their comics and read comics in my library

### Actual behavior
It loads forever while spitting out the same error in the console multiple times:

Uncaught (in promise) Error: Request failed with status code 500
    exports createError.js:16
    exports settle.js:17
    g xhr.js:54

**Comment by Syer10** [comment]
ReadComicOnline is broken from Tachiyomis side

**Comment by AriaMoradi** [comment]
duplicate of #271
