### ISSUE TITLE
[Bug] Docker container loads with blank screen

### ISSUE THREAD

**Issue by soodoh** [AriaMoradi/Tachidesk#352]
## Device information
Running on the docker container (tag latest & preview are both not working).

## Steps to reproduce
1. `docker run suwayomi/tachidesk:latest -p 4567:4567 -v ./tachidesk:/home/suwayomi/.local/share/Tachidesk`

### Expected behavior
I expect to see the home screen UI.

### Actual behavior
The page loads with a blank screen and the following error in the console:
```
Uncaught SyntaxError: Unexpected token '<'.          2.63d04f50.chunk.js:1
Uncaught SyntaxError: Unexpected token '<'           main.855dd5ac.chunk.js:1
```

## Other details
Reposting here because the issue was closed on the docker container's repo. Issue [here](https://github.com/Suwayomi/docker-tachidesk/issues/9#issuecomment-1113362951).
Everything is working fine on version 0.6.2.

**Comment by AriaMoradi** [comment]
Try opening in another browser

**Comment by soodoh** [comment]
I have confirmed that I am seeing this issue in Chrome, Firefox & Safari when using the `latest` tag. It seems this issue has now been fixed on the `preview` tag, based on my quick local testing.
