### ISSUE TITLE
Download All Chapters Button

### ISSUE THREAD

**Issue by RaoNatu** [AriaMoradi/Tachidesk#353]
I have found out that there is no Download All Button in Tachidesk-server Browser version. 
Please add one of them, because there are lot of mangas/manhwas which have 3000+ chapters and i can't download them all one by one as it takes long time.

So, I am requesting for Download All Chapters Button so i can download them all in one click.

**Comment by Robonau** [comment]
basically a dupe of #181
also should have been posted in the webui git

**Comment by RaoNatu** [comment]
Not only on webui, There is no download all chapter buttons in any of the given UIs. Why they haven't added one yet? The First issue was added on last August

**Comment by Syer10** [comment]
Because the clients need https://github.com/Suwayomi/Tachidesk-Server/issues/181 to be implemented to even add that button

**Comment by RaoNatu** [comment]
Sooo... Is it possible? To add that button?
Sorry i don't have experience in developing desktop apps

**Comment by Robonau** [comment]
> Sooo... Is it possible? To add that button? Sorry i don't have experience in developing desktop apps

yes, but only after #181 has been implemented

**Comment by Syer10** [comment]
And even then this issue would need to be in a client's repo like WebUI, not in the server repo. Closing since wrong place
