### ISSUE TITLE
Update link version in aur repository

### ISSUE THREAD

**Issue by agdral** [AriaMoradi/Tachidesk#357]
The repository aur hasn't link of download correct. it has as link "https://github.com/Suwayomi/Tachidesk-Server/releases/download/v0.6.3/Tachidesk-Server-v0.6.3-r1087.jar" and should be "https://github.com/Suwayomi/Tachidesk-Server/releases/download/v0.6.3/Tachidesk-Server-v0.6.3-r1100.jar" 

Now, yay -S tachidesk failed 
"The requested URL returned error: 404"

**Comment by AriaMoradi** [comment]
fixed
