### ISSUE TITLE
[Meta] Looking for active contributors

### ISSUE THREAD

**Issue by AriaMoradi** [AriaMoradi/Tachidesk#360]
I started this project from my BS thesis and it's been long done now. I'm constantly busy with other projects as well so I won't be able to frequently add new features and be as active as it deserves in the development of Tachidesk projects. Therefore I'm asking the community to see if anyone is willing to help out and contribute so we can move forward and release updates faster and better.

If you know Kotlin/Back-end development(for Tachidesk-Server) or ReactJS/Front-end development(for Tachidesk-WebUI) or are willing to help and learn, you can take on different tasks and open pull requests.

### How to get started with the gig?
- Read [The Contributing Guide](https://github.com/Suwayomi/Tachidesk-Server/blob/master/CONTRIBUTING.md).
- Join the discord server for Suwayomi if you haven't already. Invite link can be found in the first page/README of this repository.
- If you need to contact me, ping `@ArMor#3028` on the Suwayomi discord server or send me an Email.

**Comment by z8512** [comment]
Gone too soon... Rest in peace. RIP

**Comment by AdmnJ** [comment]
No promises on how much time I can commit, but I like to use this project and would be willing to learn a few more skills and help out when I can. 
Joined the Discord.
<img align="center" src="https://user-images.githubusercontent.com/43836753/173273041-5065bba7-e954-42b8-9e69-afffddc55f02.gif" alt="ThumbsUpAnimeGIF" width="100">

**Comment by nishantchauhan949** [comment]
I don't know how much I'll be able to help since I know only the python backend. But I can't commit a lot of time because I also have a job. I'm already a member of the discord server.

**Comment by AriaMoradi** [comment]
> I don't know how much I'll be able to help since I know only the python backend. But I can't commit a lot of time because I also have a job. I'm already a member of the discord server.

Thanks for reaching out. I started the project as a Django developer, there are no barriers as long as you are wiling to research and learn. You can help out and open pull requests whenever you can.

**Comment by LoiHQ21** [comment]
Though I'm not a web developer, I would love to contribute to this project as well. I'm currently learning react and flutter. I also have a day job so I don't know how much I can help but I will try. Just joined the discord.

**Comment by Abhinav1217** [comment]
Webdev with 4 years of Java springboot dev, 6 years of php/node dev, 2 years of android experiance.  Just discovered this app today while searching for tachiyomi desktop options that works on linux.  Would love to contribute is you are still looking for maintainer.

**Comment by Syer10** [comment]
> Webdev with 4 years of Java springboot dev, 6 years of php/node dev, 2 years of android experiance. Just discovered this app today while searching for tachiyomi desktop options that works on linux. Would love to contribute is you are still looking for maintainer.

Of course! Feel free to join the [discord](https://discord.gg/DDZdqZWaHA) so we can talk, the previous maintainer is still avalible but just doesnt have enough time for Tachidesk.
