### ISSUE TITLE
proxy not work

### ISSUE THREAD

**Issue by MvCraK** [AriaMoradi/Tachidesk#361]
use docker image

i set socks5 proxy in server.conf，but not work

**Comment by Robonau** [comment]
if this is docker specific then it should probably go in the [docker repo](https://github.com/Suwayomi/docker-tachidesk)

**Comment by adreedom** [comment]
I achieve it in my docker: (my config)
# Socks5 proxy
server.socksProxyEnabled = true
server.socksProxyHost = "192.168.50.173"
server.socksProxyPort = "7890"
