### ISSUE TITLE
Nhentai Does not work 

### ISSUE THREAD

**Issue by Eddieleon7** [AriaMoradi/Tachidesk#362]
I cant load any chapters within a doujin from nhentai. 

Works on Tachiyomi , have already tried reinstalling the extension

**Comment by AriaMoradi** [comment]
looks like you are being blocked by cloudflare protection. Until they lower the protection there's no simple fix for this. cloudflare protection is used to block bots from accessing a website and that's essentially what Tachidesk appears as.

**Comment by Eddieleon7** [comment]
> looks like you are being blocked by cloudflare protection. Until they lower the protection there's no simple fix for this. cloudflare protection is used to block bots from accessing a website and that's essentially what Tachidesk appears as.

I see….alright understood 

thanks
