### ISSUE TITLE
[Bug] Latest and preview unable to load in Firefox

### ISSUE THREAD

**Issue by Avellea** [AriaMoradi/Tachidesk#373]
## Device information
- Tachidesk version: preview
- Server Operating System: Docker
- Server Desktop Environment: N/A
- Server JVM version: Bundled with Suwayomi Docker image.
- Client Operating System: Windows 11
- Client Web Browser: Firefox 103.0b4

## Steps to reproduce
1. Run `docker run -p 4567:4567 ghcr.io/suwayomi/tachidesk`
2. Open web browser, navigate to `localhost:4567`

### Expected behavior
Display Tachidesk webUI.

### Actual behavior
Loads for a few minutes, ultimately ending with "The connection to the server was reset while the page was loading."

## Other details
Works fine in latest Chrome for Windows.

**Comment by Robonau** [comment]
OS: linux - manjaro
Browser: Firefox 101.0.1

works fine, might just be windows FF (or newer FF versions)

**Comment by Syer10** [comment]
Docker on windows isnt connected to localhost, you have to find your WSL IP and use that

**Comment by Robonau** [comment]
> Docker on windows isnt connected to localhost, you have to find your WSL IP and use that

he said it works fine in chrome tho?

**Comment by Avellea** [comment]
> Docker on windows isnt connected to localhost, you have to find your WSL IP and use that

It works perfectly fine in chrome using both localhost and 127.0.0.1.

Quick edit to include an image: ![Screenshot](https://hakurei.reeee.ee/5AXvy8Yq7.png)
