### ISSUE TITLE
[Bug] Taking too much time to update manga titles

### ISSUE THREAD

**Issue by dashnak** [AriaMoradi/Tachidesk#383]
## Device information
- Tachidesk version: Tachidesk-Server-v0.6.3-r1100-windows-x64
- Server Operating System: Windows 10
- Server Desktop Environment: N/A
- Server JVM version: OpenJDK 8.0.3020.8
- Client Operating System: Windows 10
- Client Web Browser: Brave 1.42.86, also Electron

## Steps to reproduce
1. Click on "update"
2. Wait for manga to be updated

### Expected behavior
Update of 119 different titles should occur in a reasonable time. (Tachiyomi on my OnePlus Nord 2 5G takes around 2 minutes)

### Actual behavior
Running the debug version, I can see that Tachidesk waits over 5-7 seconds after polling each title to see if it has been updated, ends up taking around 20-25 minutes. This is not related to my internet speed or my PC's speed.

## Other details
None that I can think of.

**Comment by mastermach50** [comment]
From what I understand Tachiyomi updates manga asynchronously (i.e. multiple at the same time) while Tachidesk does this syncronously (updates one, then next and so on).

If that is the case then this should probably be a feature request.

**Comment by Trung0246** [comment]
Looks like batch update also affected instead of just updating individually.
