### ISSUE TITLE
[Feature Request] Clean cache/image stored for the reading

### ISSUE THREAD

**Issue by campana-giuseppe** [AriaMoradi/Tachidesk#391]
## What feature should be added to Tachidesk?

At the moment reading (not downloading) the various resources are downloaded to ensure they can be read, but then they are not deleted but remain on the machine. The desirable behaviour is that the material, once you exit the reading of the resource for example, is deleted.

##  Why/Project's Benefit/Existing Problem

It is problematic and time-consuming when Tachidesk is used for many resources (in addition to the consumption of space not desired by the user) as the files are together with the resources that are downloaded on purpose, so it is not possible to automate their deletion or simply delete the root folder but must be manually deleted avoiding the downloaded ones on purpose. One could also get confused or waste time in identifying the ones one that were downloaded on purpose from those downloaded simply for view them.

**Comment by Syer10** [comment]
This is now handled by sing the OS temporary folder for more things 👍
