### ISSUE TITLE
Mangahere not working

### ISSUE THREAD

**Issue by 0rn0lf** [AriaMoradi/Tachidesk#398]
Loading titels from Mangahere only shows a white screen. On iOS this is totally bugged and even if you go back, it opens the blank page again until you cant do anything and need to kill the webapp. On PC this is not the case.
I cannot see anything in the log. It grabs the correct link for the desired chapter and metadata is displayed correctly. 

I'm using the latest docker container and even tried a fresh container

Anything i can do to help troubleshooting.

**Comment by DaBenjamins** [comment]
I am experiencing this too, other sources work

**Comment by Syer10** [comment]
Mangahere uses QuickJS, which only works in specific senerios. 
1. Windows is not supported by QuickJS
2. Linux users need to find a way to install libc++.so.1, on Ubuntu do `sudo apt install libc++-dev`, on Fedora do `sudo dnf install libcxx`
3. I haven't tested MacOS yet, not sure if I will currently
4. Adding support for it in the docker container is in the works here https://github.com/Suwayomi/docker-tachidesk/pull/25

**Comment by AriaMoradi** [comment]
Fixed in v0.6.6
