### ISSUE TITLE
[Feature Request] Change the size of the image in the reader

### ISSUE THREAD

**Issue by AFKoide** [AriaMoradi/Tachidesk#400]
## What feature should be added to Tachidesk?
Tachiyomi's app for mobile allow to change how the page is displayed on the screen : adjust based on the height/length, dynamic, original image size (etc.). I think Tachidesk just need the first one : height/length.

##  Why/Project's Benefit
Some pages are simply too big for the Tachidesk. In these cases, you need to scroll to read everything, or zoom out using the browser.

###  Proposition of Code
I tried a few things in CSS, and manage to set the image based on it's height :
* I disable `min-width`. 
* I set `height`'s value at `100vh`. 
I only tested with vertical's manga pages.

I also tried modifying the other parameters, and found that setting `max-width` at `100vh` zoom out the page, less than if height had this value, but still.

**Comment by Robonau** [comment]
should probably be moved to [Tachidesk-WebUI](https://github.com/Suwayomi/Tachidesk-WebUI)

**Comment by Robonau** [comment]
though a quick solution is use a different UI, since different UIs have different readers

**Comment by AFKoide** [comment]
> should probably be moved to [Tachidesk-WebUI](https://github.com/Suwayomi/Tachidesk-WebUI)

I will do it now, thanks.

> though a quick solution is use a different UI, since different UIs have different readers

It is what I was doing up until now.
