### ISSUE TITLE
[Bug] how to fix not found when trying to open tachidesk

### ISSUE THREAD

**Issue by ChillyCrimson45** [AriaMoradi/Tachidesk#409]
when i try to launch tachidesk it always ends up saying not found on the browser or in electron any fixes?

**Comment by mahor1221** [comment]
Have you downloaded the macOS-arm64 release?
If this is the case, please download it from here for the meantime:
https://github.com/Suwayomi/Tachidesk-Server-preview/releases/tag/v0.6.5-r1124
