### ISSUE TITLE
[Feature Request] View History and full screen mode needed

### ISSUE THREAD

**Issue by machine-doll** [AriaMoradi/Tachidesk#413]
## What feature should be added to Tachidesk?
There is view history on Tachiyomi Android app. But Tachidesk didn't have this feature. Once closed the book you're reading, it's difficult to find it again when you didn't add it to your library. 
There is also a leak of full screen mode in Tachidesk Electron. On my Windows 11 laptop, the taskbar takes a lot of vertical space and makes the viewport of manga alot smaller. 

##  Why/Project's Benefit/Existing Problem
As for view history feature, you can pick up the book you've read a moments ago easier. And you don't have to add them to library if you just want to read them in a few times.  
As for full screen mode, you can have a larger viewport so you can read manga easier.

**Comment by AriaMoradi** [comment]
- One feature request per issue
- Not related to Tachidesk-server

**Comment by Robonau** [comment]
i mean pressing f11 can hardly be called a feature (f11 is the fullscreen button, common across pretty much every app)
