### ISSUE TITLE
[Bug] Covers/Thumbnails of entries in Library is mostly wrong & several are missing

### ISSUE THREAD

**Issue by ghost** [AriaMoradi/Tachidesk#420]
Tachidesk version: v0.605-r1122-linux-x64
- Server Operating System: Manjaro
- Server Desktop Environment:GNOME 42
- Server JVM version: bundled with win32 or (Example: Java 8 Update 281 or OpenJDK 8u281)
- Client Operating System: <usually the same as above Server Operating System>
- Client Web Browser: (Example: Google Chrome 89.0.4389.82) 

## Steps to reproduce
1. Go into library

### Expected behavior
Right cover/thumbnail should load

### Actual behavior
Thumbnails/covers of mangas are jumbled/not right

[SCREENSHOT](https://imgur.com/a/dyuDaom)

**Comment by AriaMoradi** [comment]
Join the discord server, ask for help there. https://discord.gg/DDZdqZWaHA
