### ISSUE TITLE
[Bug] Some manga chapters opening to blank images on Win 11

### ISSUE THREAD

**Issue by LiquidPhD** [AriaMoradi/Tachidesk#439]
## Device information
- Tachidesk version: v0.6.5-r1122-windows-x64
- Server Operating System: Windows 11
- Server Desktop Environment: N/A
- Server JVM version: Java 8 Update 841
- Client Operating System: Windows 11
- Client Web Browser: Chrome 107.0.5304.88

## Steps to reproduce
1. Open One Piece 910 (or many other chapters) from MangaReader.to using any of the three launchers.
2. Observe that even though the image seems to load, the image is blank.
3. Scroll through the chapter and see that all images are blank. This is the same for several manga. Some work and some don't.
4. Open One Piece 1065 and observe that it loads without any problems.

### Expected behavior
Manga chapter loads images properly.

### Actual behavior
Images load as blank white image. When clicking "Open Site", site can be accessed and chapters can be read without issue. When opening in Tachiyomi, the same is true. 

## Other details
I'm not sure what determines whether or not a chapter will load. I have tried a few other manga and had mixed results.

**Comment by AriaMoradi** [comment]
> When opening in Tachiyomi, the same is true.

Then this issue must be fixed in Tachiyomi. Open an issue here: https://github.com/tachiyomiorg/tachiyomi-extensions
