### ISSUE TITLE
tachidesk cannot browse colored manga

### ISSUE THREAD

**Issue by loratyan** [AriaMoradi/Tachidesk#455]
**Device information**
Tachidesk-Server Preview -v0.6.6-r1159 / Tachidesk Desktop version

**Steps to reproduce**

- Open tachidesk, go to source, select colored manga.

**Expected behavior**
It should be show the manga list

**Actual behavior**
It shows infinite loop of black screen.

**Screenshot**
![image](https://user-images.githubusercontent.com/119645057/205209424-7224ca86-ddaa-42f2-8eff-f6318c7112e4.png)

There is some problem with Tachiyomi android apps.
Hope you can fix it.
Thank you

**Comment by AriaMoradi** [comment]
Couldn't reproduce the issue, everything works fine.
