### ISSUE TITLE
[Bug] Extension Page Not Loading

### ISSUE THREAD

**Issue by ghost** [AriaMoradi/Tachidesk#468]
## Device information
- Tachidesk version: ( v0.6.6-r1159-windows-x64 )
- Server Operating System Name: ( Microsoft Windows 11 Home Single Language )
- Server Operating System Version: ( 10.0.22621 Build 22621 )
- Server Desktop Environment: N/A 
- Client Operating System: same as above Server Operating System
- Client Web Browser: 1.Google Chrome ( Version 108.0.5359.125 (Official Build) (64-bit) )      2.Brave Browser [Version 1.46.144 Chromium: 108.0.5359.128 (Official Build) (64-bit)]   3. Microsoft Edge ( Version 108.0.1462.54 (Official build) (64-bit) )

## Steps to reproduce
1. Just Open Extension Page

### Expected behavior
It should have showed different extensions to install

### Actual behavior
It showed the loading circle than blank page 

## Other details
I downloaded tachidesk's latest version on my pc when I ran it my pc showed warning I clicked continue anyway than a firewall block I allowed that also it landed me on the home page of tachidesk in my browser I navigated to the extension page when I opened it it showed me the loading circle and then it stopped it didn't showed me even a single extension and it didn't showed me any error or issue that has been occurring I searched the GitHub page and used the methods mentioned there but nothing happened then I  removed all tachidesk file from my pc and reinstalled it and tried it in different browser but the same thing happened and again same for the third browser. I thought it was a server error so I stopped trying and tried again today but back to square one the same glitch. 
![Screenshot (239)](https://user-images.githubusercontent.com/121283431/209303884-02b4b827-0837-4f0d-bbb8-81b4c98239ad.png)
![Screenshot (240)](https://user-images.githubusercontent.com/121283431/209303942-2efc221b-e8e3-4ee5-82ae-f4feacfd42db.png)
![Screenshot (242)](https://user-images.githubusercontent.com/121283431/209303963-dc43da99-29f6-4000-b7b2-100619e600fd.png)

**Comment by AriaMoradi** [comment]
You are probably downloading the jar release of tachidesk, it doesn't work with Java installed from Oracle.

Download and install the msi release or the zip release and open launchers instead of tachidesk jar

**Comment by AriaMoradi** [comment]
duplicate of #237

**Comment by ghost** [comment]
> You are probably downloading the jar release of tachidesk, it doesn't work with Java installed from Oracle.
> 
> Download and install the msi release or the zip release and open launchers instead of tachidesk jar

@AriaMoradi  I downloaded both msi and zip and tried using the launcher only, nothing happened , only then I raised the query 
in my case app or launcher are not showing any extensions
if you dont mind can you give me a guide how to solve the issue

**Comment by hitokirihahn** [comment]
[logfile.log](https://github.com/Suwayomi/Tachidesk-Server/files/10824584/logfile.log)
having exactly same problem using tachidesk docker stable-alpine image run on raspberry pi.

**Comment by skoruppa** [comment]
Same issue on Ubuntu 22.04 with a package from the official ppa. I’m using only the official launchers

@AriaMoradi are you sure this is the same issue? Description of the issues are different after all....
Logs don't indicate anything
```20:26:18.132 [DefaultDispatcher-worker-1] [39mDEBUG[0;39m suwayomi.tachidesk.manga.impl.extension.ExtensionsList - Getting extensions list from the internet
Feb 24, 2023 8:26:24 PM okhttp3.internal.platform.Platform log
INFO: --> GET https://raw.githubusercontent.com/tachiyomiorg/tachiyomi-extensions/repo/index.min.json
Feb 24, 2023 8:26:42 PM okhttp3.internal.platform.Platform log
INFO: <-- 200 https://raw.githubusercontent.com/tachiyomiorg/tachiyomi-extensions/repo/index.min.json (17938ms, unknown-length body)
```

Full Logs: [tachidesk-server-debug.txt](https://github.com/Suwayomi/Tachidesk-Server/files/11077278/tachidesk-server-debug.txt)
