### ISSUE TITLE
[Feature Request] Add flipped page/portrait mode to reader

### ISSUE THREAD

**Issue by CredibleSalamander** [AriaMoradi/Tachidesk#476]
## What feature should be added to Tachidesk?
Adding Flipped page / portrait mode to the reader
##  Why/Project's Benefit/Existing Problem
It's a very niche use case, but it would improve the reading experience for someone who wants to have the page fill the whole screen and can rotate the screen itself without going into settings. (It's my preferred method of reading on a laptop)

**Comment by AriaMoradi** [comment]
Not something we are interested in implementing, rotate your display either physically or with software

**Comment by ItsRogueRen** [comment]
I think this should be added. I have a device using a compositor that CANNOT rotate in software, period (Steam Deck game mode/Gamescope). The ONLY way would be if I could rotate the app itself and then physically rotate the device.

**Comment by Robonau** [comment]
@ItsRogueRen 
1. this was always a UI issue not a server issue
2. VUI can do this (alt + left/right arrow)

**Comment by ItsRogueRen** [comment]
> @ItsRogueRen 
> 1. this was always a UI issue not a server issue
> 2. VUI can do this
> 

AFAIK VUI still cannot rotate the app, or at least the setting is exposed in the UI.

If this is more applicable to another repo, where should I put the issue?

**Comment by Robonau** [comment]
it can rotate just fine, its not a setting, you press  alt + left/right arrow
![Image](https://github.com/user-attachments/assets/258c922e-eec4-4aee-8621-2a3f89ffd9ac)

the issue should be in the [webui repo](https://github.com/Suwayomi/Suwayomi-WebUI)
