### ISSUE TITLE
[Feature Request] Extension Configs

### ISSUE THREAD

**Issue by f0banzai** [AriaMoradi/Tachidesk#480]
Some Extensions like "Bilibili Manga" and "Baozi Manhua" in Tachiyomi have some configurable parameters.
Seems that they are not implemented in Tachidesk? 

---

## What feature should be added to Tachidesk?
Some Extensions have extra configs to support some tricky operations (Mirror Site Select, Cloudflare support, Embedded Ad Banner Removal, Image Quality Select etc.)

##  Why/Project's Benefit/Existing Problem
Support these operations to use Tachidesk better.

**Comment by AriaMoradi** [comment]
Open the source, there should be a Cog icon somewhere on the top bar, open it that there is your extension configuration.
