### ISSUE TITLE
the description and images do not work in local manga

### ISSUE THREAD

**Issue by Taio99** [AriaMoradi/Tachidesk#514]
I wanted to put a manga that I have complete on my computer as a local source and I followed the guide to put the description and the image but it seems that it is broken and does not work, any help? :(

![Captura de pantalla 2023-03-08 012930](https://user-images.githubusercontent.com/67401135/223649188-6d27fab6-e786-42be-b559-09b83e01ddf1.png)

![Captura de pantalla 2023-03-08 013009](https://user-images.githubusercontent.com/67401135/223649276-2a9c06b0-98e1-4f9c-bca5-1417d08cef85.png)

![Captura de pantalla 2023-03-08 013103](https://user-images.githubusercontent.com/67401135/223649445-755cd434-bcd7-41fb-93a7-4d7380fe80c9.png)

![_](https://user-images.githubusercontent.com/67401135/223649676-dbc2eb68-be53-4dfa-a193-8b77479f062d.png)

![Captura de pantalla 2023-03-08 013258](https://user-images.githubusercontent.com/67401135/223649791-f4768e60-84ce-4806-8179-906695858731.png)

**Comment by Syer10** [comment]
This should be fixed in the latest preview
