### ISSUE TITLE
Tachidesk Not downloading Extensions.

### ISSUE THREAD

**Issue by voatxm** [AriaMoradi/Tachidesk#524]
## Device information
- Tachidesk version: v0.7.0-r983-win64
- Server Operating System: Windows 10 x64
- Server Desktop Environment: N/A 
- Server JVM version: bundled with win32
- Client Operating System: Windows 10 x64
- Client Web Browser: Google Chrome 89.0.4389.82

## Steps to reproduce
1. First Step : Opening Extension Tab and Clicking on install on any extension.

### Expected behavior
It should start installing the extension.

### Actual behavior
Nothing is happening, my network is fast and is connected kept installing for half an hour nothing happened.

**Comment by Syer10** [comment]
#237
