### ISSUE TITLE
Incomplete/ Missing pages in chapters of downloaded manga

### ISSUE THREAD

**Issue by Moyolekes** [AriaMoradi/Tachidesk#530]
In chapters of some mangas I download or try to read online on tachidesk, there are some missing pages. When I try to read manga using tachidesk, in some chapters there are some blank pages. Even when I try to read it online, these pages remain blank, any help?

**Comment by Syer10** [comment]
Hey, do you have any examples? The [discord](https://discord.gg/DDZdqZWaHA) also might be a better place to get support
