### ISSUE TITLE
[Bug] Error when downloading CBZ from newly added manga

### ISSUE THREAD

**Issue by Rx2TF** [AriaMoradi/Tachidesk#532]
## Device information
- Tachidesk version: v0.7.0-r1197
- Server Operating System: Arch Linux x86_64
- Server Desktop Environment: Plasma 5.27.3
- Server JVM version: openjdk version "19.0.2" 2023-01-17
- Client Operating System: Arch Linux x86_64
- Client Web Browser: LibreWolf 111.0.1

## Steps to reproduce
1. Turn on CBZ download
2. Add new source
3. Add new manga from source
4. Download chapter from manga

### Expected behavior
Source and manga directory gets created and chapter downloads as CBZ

### Actual behavior
Download gets marked as "Error". "IOException: No such file or directory" printed in logs.

## Other details
Workaround:
1. Turn off CBZ download
2. Download any chapter from series
OR
Create source/manga directory manually.
Afterwards, CBZ downloads work.

**Comment by Prisoner3D** [comment]
Fixed in #499. Use the [preview build](https://github.com/Suwayomi/Tachidesk-Server-preview) which should have this fixed already.
