### ISSUE TITLE
[Bug] crash when using server.downloadsPath

### ISSUE THREAD

**Issue by N013M** [AriaMoradi/Tachidesk#544]
i want to change my download directory to "D:\Games D\New folder" nut every time i add it to <server.downloadsPath> the program won't launch i even tried to change it to another location but it’s still the same

**Comment by AriaMoradi** [comment]
provide more details, what is your current config file? what are your launcher options?

**Comment by Zeonymous** [comment]
Same.
![image](https://github.com/Suwayomi/Tachidesk-Server/assets/20764838/d3a3d84e-1fe1-48fc-ae48-fb5b0429df75)

**Comment by Syer10** [comment]
If you use backslashes you need to make them double, like "B:\\\\Books\\\\Manga\\\\Tachidesk"

**Comment by Zeonymous** [comment]
Thanks for that. I have to do the same with Logitech G Hub software when making additions to profiles. Wasn't aware this was similar.

Worked!

**Comment by Syer10** [comment]
The newer preview versions include a launcher which helps configure this properly.
