### ISSUE TITLE
[Bug] <server.conf dosen't contain other info>

### ISSUE THREAD

**Issue by hell1231** [AriaMoradi/Tachidesk#572]
![image](https://github.com/Suwayomi/Tachidesk-Server/assets/81326807/418b6f89-9927-4dbb-83bf-9759fa2827b9)
that's what inside it

**Comment by AriaMoradi** [comment]
here is the reference conf file, update it manually https://github.com/Suwayomi/Tachidesk-Server/blob/master/server/src/main/resources/server-reference.conf

**Comment by hell1231** [comment]
> 

thank you

**Comment by hell1231** [comment]
> here is the reference conf file, update it manually https://github.com/Suwayomi/Tachidesk-Server/blob/master/server/src/main/resources/server-reference.conf

can i change the local file path as well?
