### ISSUE TITLE
How do I change the location of the local library by modifying the startup script

### ISSUE THREAD

**Issue by tianshiyan1314** [AriaMoradi/Tachidesk#601]

**Comment by DaDaDaDaDaYeah** [comment]
For Windows user:

Here's an alternative way.

1. Open the .bat file named "Tachidesk Browser Launcher.bat" and make the following modification to the command line:
start "" jre/bin/javaw -Dsuwayomi.tachidesk.config.server.rootDir="(Insert Your New Location, says D:\TachideskManga)" -jar Tachidesk-Server.jar"

Note: Create a new folder at your desired location, like "D:\TachideskManga," and insert this path into the command line above to change the root directory.

2. After running the modified .bat file for the first time, you'll notice new subfolders inside "D:\TachideskManga," such as downloads, extensions, local, thumbnails, and more. The "local" folder is where Tachidesk loads your local library. To use your existing library, move your library/subfolders from "D:\Manga" to "D:\TachideskManga\local."

(Optional: I find Tachidesk-Server loads local ZIP files in a proper ascending order. For example, if you have subfolders 01, 02, and 03 inside the "MangaA" folder in "D:\TachideskManga\local," zip them as 01.zip, 02.zip, and 03.zip.)

3. Restart the Tachidesk-Server, and you will now see your local library.
