### ISSUE TITLE
[Bug] Server error 500 on AllHentai extension, manga search working, but don't load chapter

### ISSUE THREAD

**Issue by GreyAlex205** [AriaMoradi/Tachidesk#603]
## Device information
- Tachidesk version: Tachidesk-Server Stable v0.7.0
- Server Operating System: Windows 10 1809 LTSC
- Server Desktop Environment: N/A
- Server JVM version: N/A
- Client Operating System: N/A
- Client Web Browser: Google Chrome 114.0.5735.199

## Steps to reproduce
1. Open source AllHentai
2. Add any manga book
3. Get 0 chapters

### Expected behavior
On library or source search with extenshion AllHentai, manga book must open, and load chapters.

### Actual behavior
Manga book with image and description loaded, but chapters don't.

## Other details
Latest extension AllHentai tachiyomi-ru.allhentai-v1.4.37 in C:\Users\User\AppData\Local\Tachidesk\extensions
On mobile Tachiomi all works fine.
Other extension like Desu works fine.
At AllHentai signed in.
Chrome in dev mode, tell me that get request receive error 500.
![allhen real](https://github.com/Suwayomi/Tachidesk-Server/assets/81999054/3ad070f6-acb5-493e-a0ef-0b4387bc427b)
![allhen](https://github.com/Suwayomi/Tachidesk-Server/assets/81999054/43586018-604b-4da4-8e52-89f7543d342c)
![desu](https://github.com/Suwayomi/Tachidesk-Server/assets/81999054/ad42a413-92e6-46ee-aca0-8f37a5ada4e8)

**Comment by Syer10** [comment]
Для просмотра контента необходима авторизация через WebView

Authorization via WebView is required to view content

Moved to #161
