### ISSUE TITLE
[Bug] Tachidesk-Server Extension Not Working - Stuck on Loading Screen

### ISSUE THREAD

**Issue by sandip3** [AriaMoradi/Tachidesk#658]
# Issue: Tachidesk-Server Extension Not Working - Stuck on Loading Screen

**Description:** The Tachidesk-Server extension is not functioning properly; it remains stuck on the loading screen. I've tried two installation methods, but the issue persists.

## Screenshots:

- Loading screen screenshot:  
  ![Screenshot from 2023-08-14 13-41-47](https://github.com/Suwayomi/Tachidesk-Server/assets/81906269/4df08be2-a43d-4ada-98ec-cd2e75f2724a)

- Hardware specifications screenshot:  
  ![Screenshot from 2023-08-14 13-59-11](https://github.com/Suwayomi/Tachidesk-Server/assets/81906269/4fa5dc07-5062-4b6a-9c2e-9746ae809145)

### Method 1: Using Command Line (CMD)

1. Added PPA repository:
```bash
sudo add-apt-repository ppa:suwayomi/tachidesk-server
```

2. Updated package list:
```bash
sudo apt update
```

3. Installed Tachidesk-Server:
```bash
sudo apt install tachidesk-server

```

### Method 2: Using DEB File

Downloaded DEB file from ![Tachidesk-Server-v0.7.0-r1197-debian-all.deb ](https://github.com/Suwayomi/Tachidesk-Server/releases/download/v0.7.0/Tachidesk-Server-v0.7.0-r1197-debian-all.deb)

#### 📢 Attention: Kindly Respond to and Acknowledge the Issue Request from a Devoted Fan of Your Work 🌟

**Comment by Syer10** [comment]
Have you looked at the server logs? Its likely not able to connect to github for some reason

**Comment by sandip3** [comment]
> Have you looked at the server logs? Its likely not able to connect to github for some reason

How do i Check "**SERVER LOG**"

![image](https://github.com/Suwayomi/Tachidesk-Server/assets/81906269/2bc54827-10fc-42ce-8c39-34be5cfce07c)

**Comment by Defin3** [comment]
judging from your username (pardon me) you seems to be an **Indian** ( im also). Use **Cloudflare WRAP**  it solved my issue.  you can try other VPN see if it works (it should work definitely)  
also you can get see logs by launching Debug launcher which is in  Techidesk directory. (im on windows so it was Debug launcher.bat for me I dont know about linux  though.

**Comment by sandip3** [comment]
> judging from your username (pardon me) you seems to be an **Indian** ( im also). Use **Cloudflare WRAP** it solved my issue. you can try other VPN see if it works (it should work definitely) also you can get see logs by launching Debug launcher which is in Techidesk directory. (im on windows so it was Debug launcher.bat for me I dont know about linux though.

bro in linux there is complex file structer so i can't find **Debug launcher**

**Comment by sandip3** [comment]
In Ubuntu, navigating to the **Debug launcher** in the file manager can be a bit complex.

**Comment by sandip3** [comment]
> judging from your username (pardon me) you seems to be an **Indian** ( im also). Use **Cloudflare WRAP** it solved my issue. you can try other VPN see if it works (it should work definitely) also you can get see logs by launching Debug launcher which is in Techidesk directory. (im on windows so it was Debug launcher.bat for me I dont know about linux though.

In Ubuntu, navigating to the 'Debug' launcher in the file manager can be a bit complex.

**Comment by sandip3** [comment]
just now i run `tachidesk-server-debug-launcher.sh` and this is output:
```
13:36:10.648 [main] INFO  suwayomi.tachidesk.server.ServerSetup - Running Tachidesk v0.6.5 revision r1122
13:36:10.711 [main] DEBUG xyz.nulldev.ts.config.ConfigManager - Loaded config:
{
    "android" : {
        "app" : {
            "debug" : true,
            "packageName" : "eu.kanade.tachiyomi"
        },
        "files" : {
            "cacheDir" : "/home/saint/.local/share/Tachidesk/android-compat/appdata/cache",
            "codeCacheDir" : "/home/saint/.local/share/Tachidesk/android-compat/appdata/code_cache",
            "dataDir" : "/home/saint/.local/share/Tachidesk/android-compat/appdata/data",
            "databasesDir" : "/home/saint/.local/share/Tachidesk/android-compat/appdata/databases",
            "downloadCacheDir" : "/home/saint/.local/share/Tachidesk/android-compat/extappdata/downloadCache",
            "externalCacheDirs" : [
                "/home/saint/.local/share/Tachidesk/android-compat/extappdata/cache"
            ],
            "externalFilesDirs" : [
                "/home/saint/.local/share/Tachidesk/android-compat/extappdata/files"
            ],
            "externalMediaDirs" : [
                "/home/saint/.local/share/Tachidesk/android-compat/extappdata/media"
            ],
            "externalStorageDir" : "/home/saint/.local/share/Tachidesk/android-compat/extappdata",
            "filesDir" : "/home/saint/.local/share/Tachidesk/android-compat/appdata/files",
            "noBackupFilesDir" : "/home/saint/.local/share/Tachidesk/android-compat/appdata/no_backup",
            "obbDirs" : [
                "/home/saint/.local/share/Tachidesk/android-compat/extappdata/obb"
            ],
            "packageDir" : "/home/saint/.local/share/Tachidesk/android-compat/android-compat/packages",
            "prefsDir" : "/home/saint/.local/share/Tachidesk/android-compat/appdata/shared_prefs",
            "rootDir" : "/home/saint/.local/share/Tachidesk/android-compat/appdata"
        },
        "system" : {
            "isDebuggable" : true
        }
    },
    "androidcompat" : {
        "rootDir" : "/home/saint/.local/share/Tachidesk/android-compat"
    },
    "server" : {
        "basicAuthEnabled" : false,
        "basicAuthPassword" : "",
        "basicAuthUsername" : "",
        "debugLogsEnabled" : false,
        "downloadsPath" : "",
        "electronPath" : "",
        "initialOpenInBrowserEnabled" : true,
        "ip" : "0.0.0.0",
        "port" : 4567,
        "socksProxyEnabled" : false,
        "socksProxyHost" : "",
        "socksProxyPort" : "",
        "systemTrayEnabled" : true,
        "webUIEnabled" : true,
        "webUIFlavor" : "WebUI",
        "webUIInterface" : "browser"
    }
}

13:36:10.753 [main] DEBUG suwayomi.tachidesk.server.ServerSetup - Data Root directory is set to: /home/saint/.local/share/Tachidesk
13:36:11.379 [main] INFO  suwayomi.tachidesk.server.util.AppMutex - Another instance of Tachidesk is running on 127.0.0.1:4567
13:36:11.379 [main] INFO  suwayomi.tachidesk.server.util.AppMutex - Probably user thought tachidesk is closed so, opening webUI in browser again.
Gtk-Message: 13:36:11.462: Failed to load module "canberra-gtk-module"
13:36:11.480 [main] INFO  suwayomi.tachidesk.server.util.AppMutex - Aborting startup.

 ```
