### ISSUE TITLE
[Feature Request] Sort by last read

### ISSUE THREAD

**Issue by ShuaybM** [AriaMoradi/Tachidesk#663]
## What feature should be added to Tachidesk?
A 'By last read' sort filter to add to the existing ones. So whichever entry was last read will appear in order.

##  Why/Project's Benefit/Existing Problem
Organises the library in a user-friendlier way (though I get that others like the existing sorts) so that it's easier to pick up whatever series you last read

**Comment by schroda** [comment]
this belongs to https://github.com/Suwayomi/Tachidesk-WebUI

and it's already included in the preview version https://github.com/Suwayomi/Tachidesk-WebUI-preview/releases/tag/r1168 or https://tachidesk-webui-preview.github.io/
