### ISSUE TITLE
[Bug] Pages not in order

### ISSUE THREAD

**Issue by MAS4RADIA** [AriaMoradi/Tachidesk#690]
## Device information
- Tachidesk version: v0.7.0-r1197-debian-all
- Server Operating System: Debian 12
- Server Desktop Environment: KDE
- Server JVM version: OpenJDK 17.0.8+7-Debian-1deb12u1
- Client Operating System: Debian 12
- Client Web Browser: Google Chrome, Firefox, Tachidesk Sorayomi (and most likely all of them)

## Steps to reproduce
1. Launch server
2. Read Manga

### Expected behavior
Normal page order.

### Actual behavior
Pages load and shown in a disorderly manner. The cover page goes around last and the last page in the middle. Well, it's all messed up. There probably isn't a single page that's in order.

## Other details
When downgraded to v0.6.6-r1159, everything works just fine. Problem is the extensions (when downgraded).

**Comment by Syer10** [comment]
This is a known issue with the stable build, it is fixed in the preview builds if you would like to use them https://github.com/Suwayomi/Tachidesk-Server-preview/releases
