### ISSUE TITLE
[Bug] i have a problem in tachidesk 

### ISSUE THREAD

**Issue by ayoubyuan** [AriaMoradi/Tachidesk#691]
**I have chapters that i downloaded from tchiyomi if i want to transfer these chapters to tachidesk the app dont read them any solution to this problem**

**Comment by Syer10** [comment]
Put them in the local source if you want to guarantee that you can read them. https://github.com/Suwayomi/Tachidesk-Server/wiki/Local-Source

Otherwise if you try to download them, Tachidesk might recognize that they are downloaded and mark it as downloaded immanently.
