### ISSUE TITLE
[Bug] Timeout on Tachiyomi chapters listing

### ISSUE THREAD

**Issue by alexandrejournet** [AriaMoradi/Tachidesk#733]
## Device information
- Tachidesk version: docker-tachidesk stable v0.7.0
- Server Operating System: Debian
- Server Desktop Environment: N/A
- Server JVM version: default
- Client Operating System: Debian
- Client Web Browser: Latest chrome

## Steps to reproduce
1. On Tachiyomi, when the chaptersList is huge (1300+), the onlineFetch takes to much time and I got a timeout.
2. On Postman it works, so I can put screenshots.

### Expected behavior
We should get the list of chapters.

### Actual behavior
Got a Socket Timeout Exception

## Other details
![image](https://github.com/Suwayomi/Tachidesk-Server/assets/10961290/7c289921-dded-427b-9cb8-489271b64ca0)

**Comment by Syer10** [comment]
`onlineFetch` means its fetching chapters from the source, if the source takes too long to give us the chapters it can timeout, what do you suggest we do? I feel like the timeout is a good way to handle this.

**Comment by alexandrejournet** [comment]
It's taking way too much time in my opinion, i cant fetch them in tachiyomi even with a Timeout of 2 minutes... :/

I will try to fix it ^^

**Comment by Syer10** [comment]
Tachidesk is waiting on the source to return chapters, it sounds like you are using a slow source, have you tried others?

**Comment by alexandrejournet** [comment]
It's working for my others mangas, it's only this one with 1300+ files which takes too much time, and I think I'm not the only one having this timeout problem on a huge library :/

**Comment by alexandrejournet** [comment]
I'm going to audit the code and check if there's not too many connections to the databases, or too many inserts one by one instead of a list insert, something like this to optimise the request

**Comment by Syer10** [comment]
Hmm, its possible the chapter sync logic could be inefficient, I forgot about that. If you find a problematic section let us know.

**Comment by alexandrejournet** [comment]
I will ! And I'll try to make a pr

**Comment by alexandrejournet** [comment]
@Syer10 This issue can be closed, with the latest preview it worked. With PR #737
