### ISSUE TITLE
[Bug] Unable to switch server webui to preview channel

### ISSUE THREAD

**Issue by qu1ck** [AriaMoradi/Tachidesk#740]
## Device information
- Tachidesk version: v0.7.0-r1393
- Server Operating System: official docker image
- Server Desktop Environment: N/A
- Server JVM version: bundled with docker image

## Steps to reproduce
1. Change the `server.webUIChannel` to `"preview"`
2. Restart server
3. Setting is reverted back to `"stable"` and webui is not updated.

### Expected behavior
Server should update the webui to preview version

### Actual behavior
Nothing happens and the setting is reverted back.

**Comment by Syer10** [comment]
If you are using the Docker version, you need to configure the server using the Environment variables in the README.
