### ISSUE TITLE
[Bug] Tachidesk serving javascript with wrong mime type

### ISSUE THREAD

**Issue by qu1ck** [AriaMoradi/Tachidesk#758]
## Device information
- Tachidesk version: v0.7.0-r1411
- Server Operating System: docker image
- Server Desktop Environment: N/A
- Server JVM version: bundled with docker image
- Client Operating System: Windows
- Client Web Browser: chrome 119.0.6045.105

## Steps to reproduce
This does not happen immediately after server is started. But after a day or a few (possibly related to webui auto updating) this starts happening:
1. Load the front page - loads fine
2. Open any of the tabs or mangas in a new tab - white screen
When inspecting browser dev console of a white screen the following error is shown:
```
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
```

Checking network tab shows that it indeed serves index-xxxxx.js as text/html

For some reason the same file is served as application/javascript if I load the root url and the page works. For any other url - white screen.

### Expected behavior
Pages load

### Actual behavior
Browser complains about wrong mime type for javascript and refuses to load the page.

**Comment by Syer10** [comment]
@schroda Any ideas?

**Comment by schroda** [comment]
nope, but someone else runs into the same issue ([support thread in discord](https://discord.com/channels/801021177333940224/1170658014731182170)) and uses docker as well, so maybe connected to docker?
