### ISSUE TITLE
[Feature Request] Adjust CBZ naming scheme

### ISSUE THREAD

**Issue by ejkarne** [AriaMoradi/Tachidesk#768]
## What feature should be added to Tachidesk?

The CBZ naming scheme should be adjusted so that the name of the scanlator comes after the chapter number or chapter titles. Either by default or configurable via server.conf.

##  Why/Project's Benefit/Existing Problem

On devices that do not have access to a Tachidesk client (like e-readers) a common solution is mounting/syncing the download directory to the device. This works well but because of the default naming scheme it's not guaranteed to be in the correct order for reading.

**Comment by benticlaskaris** [comment]
+1. Using kavita, komga or other manga scrapers produces bad results since the scanlator is before and it is read as series name. I'm gonna try to do a pull requests in case next days

**Comment by benticlaskaris** [comment]
PR submitted. Already checked with komga, kavita and with this naming gets picked up correctly.

**Comment by Syer10** [comment]
This sounds like a job for another application. We plan to keep the downloads using the same scheme as Tachiyomi. Tachidesk is mainly meant to be an all-in-one application, so the naming scheme is based on our needs.

If you want to copy them elsewhere, your best chance is to create a script/program that uses the api, that matches the chapters to the downloaded files, and then copies them elsewhere based on your naming scheme.

**Comment by ejkarne** [comment]
> This sounds like a job for another application. We plan to keep the downloads using the same scheme as Tachiyomi. Tachidesk is mainly meant to be an all-in-one application, so the naming scheme is based on our needs.
> 
> If you want to copy them elsewhere, your best chance is to create a script/program that uses the api, that matches the chapters to the downloaded files, and then copies them elsewhere based on your naming scheme.

That's fair. I consider this feature request sort of a stopgap solution for devices that lack Tachidesk clients like e-readers where https://github.com/Suwayomi/Tachidesk-Server/issues/769 would end up being a better permanent solution.

Though for e-readers that aren't compatible or have poor implementations, setting unreads to auto download and just mounting the server is a quick and easy solution that would benefit from a configurable naming scheme.

**Comment by taos15** [comment]
Now that tachiyomi is mot more, can this issue be resolved-looked?

**Comment by AriaMoradi** [comment]
> Now that tachiyomi is mot more, can this issue be resolved-looked?

We have changed our upstream/reference from Tachiyomi to Mihon, and as Syer said we want to maintain compatibility with them where possible and that includes file naming scheme.
