### ISSUE TITLE
[Bug] Tray icon does not appear on KDE wayland

### ISSUE THREAD

**Issue by chrrybmb64** [AriaMoradi/Tachidesk#777]
## Device information
- Tachidesk version: v0.7.0-r1197
- Server Operating System: Arch Linux
- Server Desktop Environment: KDE wayland
- Server JVM version: openjdk 21
- Client Operating System: Arch Linux
- Client Web Browser: Firefox

## Steps to reproduce
1. First Step

install tachidesk via the `tachidesk` aur package

2. Second Step

run tachidesk

### Expected behavior

when tachidesk is running, the tray icon appears in the taskbar

### Actual behavior

the tray icon does not appear despite tachidesk running

## Other details

the tray icon appears when using x11, i could only produce this bug on wayland.

**Comment by Throun** [comment]
For me, I solved this issue by installing `appmenu-gtk-module`.

**Comment by chrrybmb64** [comment]
> For me, I solved this issue by installing `appmenu-gtk-module`.

still no tray icon for me.

**Comment by Robonau** [comment]
given you closed it.
did you find a fix?
if so what was it

**Comment by chrrybmb64** [comment]
i closed the issue because nobody else reported having this bug and i no longer use this software. if you have it feel free to make a new issue.

**Comment by FeyrisTan** [comment]
New user here. Using Arch linux (yeah gotta mention that) Wayland KDE. Running it through the terminal immediately tells u what you're missing.
In my case: libappindicator-gtk3
