### ISSUE TITLE
[Bug] I got 404 error

### ISSUE THREAD

**Issue by dnet890** [AriaMoradi/Tachidesk#805]
---

## Device information
- Suwayomi-Server version: v0.7.0-r1446
- Server Operating System: Ubuntu 22.04
- Server Desktop Environment: N/A or KDE
- Server JVM version: bundled
- Client Operating System: Kubuntu
- Client Web Browser:Brave 1.6

## Steps to reproduce
1. download https://github.com/Suwayomi/Suwayomi-Server-preview/releases/download/v0.7.0-r1446/Suwayomi-Server-v0.7.0-r1446-debian-all.deb
2. Launch the app and I got error

### Expected behavior
it should works

### Actual behavior
I understand that tachiyomi extension is gone and we have to rely on external sources. But, I download the latest version and it does not worked

![2024-01-09_14-13_1](https://github.com/Suwayomi/Suwayomi-Server/assets/29157187/5d851ed7-fa40-4b00-b637-6062d387549d)
![2024-01-09_14-13](https://github.com/Suwayomi/Suwayomi-Server/assets/29157187/b5da281c-b775-4c21-b57c-0ab72fd6b7e3)

**Comment by Robonau** [comment]
if you are using the preview version of the server you should be using the preview version of webui too

**Comment by Robonau** [comment]
server address is not the external repo option
changing it in the way you did just stops the client from accessing the server

**Comment by dnet890** [comment]
So, I download the apk from external repo by click the plus button and I tried to add the external repo site. But, it is been greyed out 
![image](https://github.com/Suwayomi/Suwayomi-Server/assets/29157187/0a70f3f1-b591-4a6b-be8d-cdb1e3c9ab28)
![image](https://github.com/Suwayomi/Suwayomi-Server/assets/29157187/b3454910-07a0-416a-82e4-9c01abd0f2f9)

**Comment by Robonau** [comment]
just use the github url
`https://github.com/keiyoushi/extensions/`
the tailing `/` is important currently

**Comment by Robonau** [comment]
you still haven't set webui to preview

**Comment by dnet890** [comment]
![image](https://github.com/Suwayomi/Suwayomi-Server/assets/29157187/d19cd911-9ea5-4939-8951-251833fa4f02)
Is that what you mean? But, it does not worked

**Comment by Robonau** [comment]
yes, thats what i meant, if you go to extensions you should see the repo in the extension card like so
![image](https://github.com/Suwayomi/Suwayomi-Server/assets/30987265/1c17dde8-dd57-42c5-a66f-7cfef729d8db)

**Comment by dnet890** [comment]
Hmm, I cannot find new manga Do, I need to download the apk and load it manually on the launcher?
![2024-01-09_14-51](https://github.com/Suwayomi/Suwayomi-Server/assets/29157187/d305b18c-2a06-4ecf-a3de-8fb2987c4f9f)
![2024-01-09_14-50](https://github.com/Suwayomi/Suwayomi-Server/assets/29157187/a8d33f35-5776-41d8-9618-826f97d241ce)

**Comment by Robonau** [comment]
no,if you have the repo setting set then you should be able to install extensions from said repo in the extensions tab

1. install extension u want from the extensions tab
2. browse source from the source tab
3. open manga

**Comment by dnet890** [comment]
do you mean download apk from the github and sideload it manually like this? because that one works
![image](https://github.com/Suwayomi/Suwayomi-Server/assets/29157187/19937bc6-51de-4614-9d8b-cbd33ff500a4)

![image](https://github.com/Suwayomi/Suwayomi-Server/assets/29157187/823d5a4c-5b92-4489-9445-b75b219601bc)

**Comment by Robonau** [comment]
when i said `no` the first time you asked that question i meant `no`

**Comment by Robonau** [comment]
if you don't want the repo updates then you can do it manually like you have and itl work for as long as it works

**Comment by dnet890** [comment]
that means something wrong with the app because it cannot fetch external repo like the Android version and the only way is sideload it from the apk

**Comment by Robonau** [comment]
no, it works fine

**Comment by dnet890** [comment]
I use Linux maybe you use different OS. that could means different

**Comment by Robonau** [comment]
no, im also linux, debian based too at that

**Comment by Robonau** [comment]
given what you were doing at the start of this issue i can only assume you are doing something obviously wrong but just not showing it

**Comment by dnet890** [comment]
yeah, it works. But, the load process is longer than usual
