### ISSUE TITLE
[meta] Tachiyomi is dead.

### ISSUE THREAD

**Issue by ghost** [AriaMoradi/Tachidesk#824]
Tachiyomi development has ended. There will be no further updates or bug fixes. The extension repository has been shut down, so Tachidesk does not work properly either. Will Suwayomi server continue development, or will you stop and rewrite everything to Kotatsu sources or create your own scrappers?

![image](https://github.com/Suwayomi/Suwayomi-Server/assets/151369913/ae419b5e-439d-45bd-bc56-78a196ac0d9b)

![image](https://github.com/Suwayomi/Suwayomi-Server/assets/151369913/2ea93bd2-0742-4ac1-9ef9-1d277821367b)

![image](https://github.com/Suwayomi/Suwayomi-Server/assets/151369913/a4f3c278-c294-446e-9146-9af14e9a8d32)

**Comment by Robonau** [comment]
preview already has support for external repositories of extensions.
Suwayomi currently works as it did before.
Suwayomi will continue development.
we wont be rewriting any extensions, we will continue to rely on the 3rd party tachiyomi extension repositories

**Comment by ghost** [comment]
@Robonau thanks for response.

**Comment by L00maca** [comment]
@UntrustedContributor  there are already repositories for extensions available and updated and a working fork of Tachiyomi, plus other forks like TachiyomiSY are all alive and well. I don't foresee any issue for Suwayomi to source up to date extensions anytime soon.
