### ISSUE TITLE
[Bug] No extension in the extensions list

### ISSUE THREAD

**Issue by FaintShadow** [AriaMoradi/Tachidesk#827]
## Device information
- Suwayomi-Server version: v0.7.0
- Server Operating System: Windows 11 Pro 22H2 22621.2861 
- Server Desktop Environment: N/A
- Server JVM version: bundled with win32
- Client Operating System: same as the above
- Client Web Browser: [Brave] Version 1.61.116 Chromium: 120.0.6099.217 (Official Build) (64-bit)

## Steps to reproduce
1. Install Tachidesk from the release's .msi file

### Expected behavior
Find the list of extensions in the extensions tab (either using the Tachidesk included webui or app)

### Actual behavior
nothing in the extensions list

## Context
There is nothing in the wiki that shows how to install extensions or what the extension format is etc...
I've read the comments in issue #824 but it doesn't mention anything

![image](https://github.com/Suwayomi/Suwayomi-Server/assets/153730465/fe520354-b4d5-4ce7-bc73-17c9043acbfc)

**Comment by Robonau** [comment]
extensions are no longer shipped with the application, you will need to add your own repo (or find a public one), you will need to be using preview to do this

**Comment by FaintShadow** [comment]
> extensions are no longer shipped with the application, you will need to add your own repo (or find a public one), you will need to be using preview to do this

@Robonau how do I do that ? there is no tutorial or guide and there is no place in the interface to put a repo

**Comment by Robonau** [comment]
> > extensions are no longer shipped with the application, you will need to add your own repo (or find a public one), you will need to be using preview to do this
> 
> @Robonau how do I do that ? there is no tutorial or guide and there is no place in the interface to put a repo

using the latest preview.
if u are using the launcher there is an extensions tab where you can add your repo `https://github.com/foo/bar`
or you can add it via server settings in the preview channel webui

if u are using docker then itl be an env variable like everything else

**Comment by FaintShadow** [comment]
> > > extensions are no longer shipped with the application, you will need to add your own repo (or find a public one), you will need to be using preview to do this
> > 
> > 
> > @Robonau how do I do that ? there is no tutorial or guide and there is no place in the interface to put a repo
> 
> using the latest preview. if u are using the launcher there is an extensions tab where you can add your repo `https://github.com/foo/bar` or you can add it via server settings in the preview channel webui
> 
> if u are using docker then itl be an env variable like everything else

@Robonau where do I need to add the repo ? there is only a "+" button which will open a file selector I tried to add a file called ["index.min.json"](https://github.com/keiyoushi/extensions/blob/repo/index.min.json) but it didn't work. and also when you said "preview" do you mean "debug" version ?

**Comment by Robonau** [comment]
> @Robonau where do I need to add the repo ? there is only a "+" button which will open a file selector I tried to add a file called ["index.min.json"](https://github.com/keiyoushi/extensions/blob/repo/index.min.json) but it didn't work. and also when you said "preview" do you mean "debug" version ?

by preview i mean [preview](https://github.com/Suwayomi/Suwayomi-Server-preview/releases)

**Comment by FaintShadow** [comment]
@Robonau I installed the preview and everything, I added the repo to the extensions tab but still it doesn't work. Can you give me a repo that you use rn so I can test and see if it work on my machine ?

**Comment by Robonau** [comment]
> @Robonau I installed the preview and everything, I added the repo to the extensions tab but still it doesn't work. Can you give me a repo that you use rn so I can test and see if it work on my machine ?

no

**Comment by FaintShadow** [comment]
@Robonau thanks for your help, I finally made it work I added both [1](https://github.com/keiyoushi/extensions) and [2](https://github.com/keiyoushi/extensions-source) links to the extensions using the extensions tab and It works now.
