### ISSUE TITLE
Extensions do not appear

### ISSUE THREAD

**Issue by ccode-iin** [AriaMoradi/Tachidesk#831]
The Extensions do not appear for me so I can install them. What is the problem ?
![Screenshot 2024-01-17 153206](https://github.com/Suwayomi/Suwayomi-Server/assets/97261216/83994364-c97f-4820-aee8-f26accb3c276)

**Comment by Robonau** [comment]
with tachiyomi removing its extensions repo external repos have become a requirement

with the **PREVIEW** version of Suwayomi-Server.

Here is how to configure it
Suwayomi-Server option 1: With the new launcher, go to the Extensions tab and add the extensions repo.
Suwayomi-Server option 2: Go to the server.conf file in the data files and add the extensions repo.
Suwayomi-Server option 3: Use the server settings in WebUI to add the extensions repo(requires WebUI preview).

youl need to find your own repo tho

**Comment by dattebayoed** [comment]
hello, a new member of tachidesk, old user of tachiyomi, also facing the same issue of extensions not appearing! What does it mean by extension repo, where can I get them and how can I add them?

**Comment by Robonau** [comment]
> hello, a new member of tachidesk, old user of tachiyomi, also facing the same issue of extensions not appearing! What does it mean by extension repo, where can I get them and how can I add them?

please read the first response message

**Comment by withercreeper25** [comment]
same..help..what is expo extension?

**Comment by Robonau** [comment]
> same..help..what is expo extension?

please read the first response message

**Comment by Robonau** [comment]
@Syer10 for the love of god close this issue
