### ISSUE TITLE
[Bug] Can't install extensions from repo nor external files

### ISSUE THREAD

**Issue by TyrantRC** [AriaMoradi/Tachidesk#847]
## Device information
- Suwayomi-Server version: Preview v0.7.0-r1468x64 windows
- Server Operating System: Windows 10 Pro N 22H2 19045.3930 x64
- Server Desktop Environment: N/A
- Server JVM version: build 17.0.8+9-LTS-211
- Client Operating System: Same as server
- Client Web Browser: Google Chrome Version 121.0.6167.86 (Official Build) (64-bit)

## Steps to reproduce
1. try to install an extension from either a repo or an external file

### Expected behavior
should install the extension and be able to use it

### Actual behavior
[sends back a error message](https://i.imgur.com/Y76qIWn.jpeg)

## Other details
This happens with any extension, be it from a repo, or an external file. I can install anything on the stable version, but it was suggested in other issues to install to the latest preview since some extensions were malfunctioning in the stable.

Attached a log of me trying to do it from a fresh install
[application.log](https://github.com/Suwayomi/Suwayomi-Server/files/14031606/application.log)

**Comment by Robonau** [comment]
@Syer10 line 174, should that be a .jar or should that be an .apk?
`2024-01-23 21:43:23.031 [DefaultDispatcher-worker-10] ERROR suwayomi.tachidesk.manga.impl.util.PackageTools - Failed to load jar with path: E:\Images\Manga\#Suwayomi\Data/extensions/tachiyomi-all.mangadex-v1.4.192.jar`
edit: ignore me

**Comment by Syer10** [comment]
@TyrantRC you need to remove the # from the path, that special character will likely break a few things.

**Comment by TyrantRC** [comment]
> @TyrantRC you need to remove the # from the path, that special character will likely break a few things.

This solved the issue. Thanks.

changed root path from "E:\Images\Manga\\#Suwayomi" to "E:\Images\Manga\Suwayomi".
