### ISSUE TITLE
[Feature Request] Add NixOS setup guide

### ISSUE THREAD

**Issue by RatCornu** [AriaMoradi/Tachidesk#858]
## What feature should be added to Suwayomi?
Add a NixOS section in the README to install suwayomi-server.

##  Why/Project's Benefit/Existing Problem
In the same way as Arch Linux, Debian/Ubuntu, ... it could be interesting to mention in the README that NixOS has a package and a module making easy the setup of Suwayomi-Server.

If necessary, I can give more explanations and a code snippet to install suwayomi-server.

**Comment by airi019** [comment]
?? where is it? I can't find it on search.nixos.org

**Comment by AriaMoradi** [comment]
None of the developers use NixOS, PRs are welcome.

**Comment by RatCornu** [comment]
Okay I will make a PR for this ! I will probably wait for the version 1.0.0 to release and make a PR on nixpkgs before doing it.

**Comment by Syer10** [comment]
Feel free to do a PR whenever, 1.0.0 is out now 👍
