### ISSUE TITLE
[Bug] Preview Server Doesn't work offline

### ISSUE THREAD

**Issue by FaintShadow** [AriaMoradi/Tachidesk#861]
## Device information
- Suwayomi-Server version: Suwayomi-Server-v0.7.0-r1461
- Server Operating System: Windows 11 64x
- Server Desktop Environment: N/A
- Server JVM version: bundled with win32
- Client Operating System: same as above Server Operating System
- Client Web Browser: Chromium: 121.0.6167.139

## Steps to reproduce
1. turn off wifi/internet
2. restart computer
3. make sure the internet is still closed
4. open suwayomi server
5. select either web or electorn

### Expected behavior
open the usual UI

### Actual behavior
when selecting electron, I get the system tray Icon of the server but electron doesn't open automatically. When I open it fron the system tray all I get is the window with a blank (white) screen. When selecting the webUI I get a Unable to connect (basically as if the local IP address doesn't exist)

## Other details
When opening the server with Internet access then closing it, then stopping the internet/wifi then reopening it it works fine.

**Comment by Robonau** [comment]
was fixed by Suwayomi/Suwayomi-Server/pull/849 v0.7.0-r1472
r1461 is an old version
[v0.7.0-r1480](https://github.com/Suwayomi/Suwayomi-Server-preview/releases/tag/v0.7.0-r1480) is current

**Comment by FaintShadow** [comment]
> was fixed by [/pull/849](https://github.com/Suwayomi/Suwayomi-Server/pull/849) v0.7.0-r1472 r1461 is an old version [v0.7.0-r1480](https://github.com/Suwayomi/Suwayomi-Server-preview/releases/tag/v0.7.0-r1480) is current

why isn't there a autoUpdate button in the server ? or should I request that as a feature ?

**Comment by Robonau** [comment]
> why isn't there a autoUpdate button in the server ? or should I request that as a feature ?

go for it, though i doubt it'l happen any time soon

**Comment by Kaehvaman** [comment]
Please reopen this issue because it still happens on the latest version. Server/Client on Windows 10 22H2. Browsers: Yandex Browser 25.8.3.824 (64-bit) and Firefox 135.0.1

PS: WebUI works if there is internet but Electron is always blank, should I open a new issue?

Suwayomi version screeenshot:
<img width="595" height="1121" alt="Image" src="https://github.com/user-attachments/assets/b7991aa8-6b0f-46c9-9731-80dc9242b4a2" />

**Comment by FaintShadow** [comment]
@Kaehvaman Is it fixed yet, if not I will reopen this issue.

**Comment by Kaehvaman** [comment]
> [@Kaehvaman](https://github.com/Kaehvaman) Is it fixed yet, if not I will reopen this issue.

I suppose the dev called it a wontfix. Because this happens due to incompatibility between downloaded and bundled WebUI versions.
