### ISSUE TITLE
[Feature Request] Extension Repositories (current situation)

### ISSUE THREAD

**Issue by ilonachan** [AriaMoradi/Tachidesk#862]
## What feature should be added to Suwayomi?
Since the recent developments with Tachiyomi, extensions are no longer distributed from their central location, but instead through a general repository format for which links need to be manually added to Tachiyomi/Mihon. Support for this should be added to Suwayomi as well, as soon as possible. Possibly on first startup a choice should be given to pre-register one of the (as far as I can tell) two big extension repositories, or the fact that this is necessary should be mentioned somewhere in documentation.

##  Why/Project's Benefit/Existing Problem
Currently there doesn't seem to be any way to install the commonly used extensions, other than manually uploading their APKs. It might even be difficult for a new user to find out that this option exists, since installation of APKs in PC software is uncommon and the documentation never mentions it. Either way, the ease of use of downloading extensions straight from the app itself should be preserved.

**Comment by Robonau** [comment]
its been in preview since the day before tachiyomi shut down
(its mentioned all over the place in the discord)

**Comment by ilonachan** [comment]
ah ok, sorry then. I tried the preview docker image tho, and it didn't have it, so is that just very out of date?

**Comment by Robonau** [comment]
no, it has it
ya can set it in the preview channel webui
or ya can use a docker env as explained in the docker preview readme

**Comment by ilonachan** [comment]
oh ok it does. In the global settings, in a category called "Browse", which on enter is actually the "Extensions" category. I'm not gonna fault myself for not finding that. It'd be great if the documentation could make it clear that this setting exists, where it is, and that you need to set it to properly use Suwayomi.

...actually should I keep this issue open and rephrase it as "this feature exists, but it's not clear enough where to find it"?
