### ISSUE TITLE
Suwayomi Showing error 500

### ISSUE THREAD

**Issue by Divyam-Naudiyal** [AriaMoradi/Tachidesk#864]
In the Library section it is showing this error
Could not load categories
Network Error
Secondly it not opening any extensions 
And lastly i am unable to create backup
![Screenshot 2024-02-05 205346](https://github.com/Suwayomi/Suwayomi-Server/assets/118731194/c50014b8-4131-499b-8f5c-b741b53fc5e0)

**Comment by Robonau** [comment]
1. you are on an old version, you should be using preview with preview channel webui
2. with tachiyomi no longer having a default extensions repo suwayomi followed, you will have to find and add you own extension repo to get extensions from
3. 1 should fix that

**Comment by Divyam-Naudiyal** [comment]
IT is showing this 
![Screenshot 2024-02-05 223534](https://github.com/Suwayomi/Suwayomi-Server/assets/118731194/b3598b75-5bc7-4e16-ac10-630970671015)
And i am unable to preview sources and extensions and iam unable to clear the cache in the server

**Comment by Robonau** [comment]
> IT is showing this ![Screenshot 2024-02-05 223534](https://private-user-images.githubusercontent.com/118731194/302371498-b3598b75-5bc7-4e16-ac10-630970671015.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNTQ2OTMsIm5iZiI6MTcwNzE1NDM5MywicGF0aCI6Ii8xMTg3MzExOTQvMzAyMzcxNDk4LWIzNTk4Yjc1LTViYzctNGUxNi1hYzEwLTYzMDk3MDY3MTAxNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNVQxNzMzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NmEwZjk4NWJiNjUzZTUzODJhNTkwMzA0NzgxOTg3OTRjYTRlYmY3Yjc0N2JjMDRmMzU2N2VhNjRkYjYxMzAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.b-hVfA02fTYnrCwrC5ZdXMU3Aef5YtkoP0EsdddC8jk) And i am unable to preview sources and extensions and iam unable to clear the cache in the server

i have already told you what you need to do
if u aint gonna do it nothing is gonna help you

**Comment by Divyam-Naudiyal** [comment]
bro i have downloaded the latest version and in it not adding extensions and showing error

**Comment by Syer10** [comment]
Please download the latest preview version https://github.com/Suwayomi/Suwayomi-Server-preview/releases

**Comment by Syer10** [comment]
Then do this
1. Find an extensions repo, there is now no default extensions and you have to use google to find a Tachiyomi extension repo.
    - Note: The repo should look like https://raw.githubusercontent.com/user/reponame or https://www.github.com/user/reponame
2. Configure it using one of the following:
    - Suwayomi-Server option 1: With the new launcher, go to the Extensions tab and add the extensions repo.
    - Suwayomi-Server option 2: Go to the server.conf file in the data files and add the extensions repo.
    - Suwayomi-Server option 3: Use the server settings in WebUI to add the extensions repo(requires WebUI preview channel).
    - Suwayomi docker container: Edit the EXTENSION_REPOS environment variable and add the extension repo in the format listed in the container README.

**Comment by Divyam-Naudiyal** [comment]
![Screenshot 2024-02-05 231233](https://github.com/Suwayomi/Suwayomi-Server/assets/118731194/83cb17c2-ed33-46da-a5c0-59e8b1e70137)
I have downloaded it already

**Comment by bosskham** [comment]
> 1. you are on an old version, you should be using preview with preview channel webui
> 2. with tachiyomi no longer having a default extensions repo suwayomi followed, you will have to find and add you own extension repo to get extensions from
> 3. 1 should fix that

Dude it's a bug don't you listen to @Divyam-Naudiyal at all? It's a bug that he's try to find the solution and it's the latest suwayomi server + webui, you are totally idiot @Robonau

**Comment by bosskham** [comment]
> IT is showing this ![Screenshot 2024-02-05 223534](https://private-user-images.githubusercontent.com/118731194/302371498-b3598b75-5bc7-4e16-ac10-630970671015.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MjE1MjAsIm5iZiI6MTcyOTUyMTIyMCwicGF0aCI6Ii8xMTg3MzExOTQvMzAyMzcxNDk4LWIzNTk4Yjc1LTViYzctNGUxNi1hYzEwLTYzMDk3MDY3MTAxNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQxNDMzNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYzQ4ZTJhZGRhMmY1MGQ1OWY4NDdlZjE1MTNkMzRiZGQ0NTg4OTM4OTVlYmUzZDMwMzJjNmJlZWE1M2E0YTFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.h1foQx3PwSJRme6ElZq3y2QwGEE6ExY66gFLHRo8fUM) And i am unable to preview sources and extensions and iam unable to clear the cache in the server

![Untitled](https://github.com/user-attachments/assets/cf46bdbe-b174-4739-8950-51fc18347087)

You probably turn on basic Authentication which is requre to login to access library, you can turn it off by uncheck this and restart the server again

**Comment by Robonau** [comment]
> 
> Dude it's a bug don't you listen to @Divyam-Naudiyal at all? It's a bug that he's try to find the solution and it's the latest suwayomi server + webui, you are totally idiot @Robonau

1. it was/is not a bug, it was a change in how the program worked that broke older versions
2. he was not using the preview version that at the time worked correctly when the release version didn't (due to the aforementioned change)
3. there has been like 3 releases since this issue was made all of which work as intended in regards to extensions
4. please avoid personal attacks
5. the issue has long since been resolved hence it being closed by the author 8 months ago
6. if you are running in to a similar issue please make a new issue
