### ISSUE TITLE
[Bug] Local source disappears with server error after browsing other extension

### ISSUE THREAD

**Issue by kairakyu** [AriaMoradi/Tachidesk#866]
## Device information
- Suwayomi-Server version: v0.7.0-r1480
- Server Operating System: bundled in docker image (ghcr.io/suwayomi/tachidesk)
- Server Desktop Environment: N/A
- Server JVM version: bundled in docker image
- Client Operating System: Linux (as docker host)
- Client Web Browser: Firefox 122.0

## Steps to reproduce
1. Run using docker-tachidesk [docker-compose.yml](https://github.com/Suwayomi/docker-tachidesk/blob/main/docker-compose.yml), adding these environment vars:
```yaml
      - WEB_UI_CHANNEL=preview
      - DOWNLOAD_AS_CBZ=true
      - FLARESOLVERR_ENABLED=true
      - FLARESOLVERR_URL=http://flaresolverr:8191
```
Open Web UI and view the "Browse" page, looks okay:
![1_local_source_exists](https://github.com/Suwayomi/Suwayomi-Server/assets/159391018/f267fc3f-9220-498e-940d-7dcdf7e105be)
2. Configure third-party extension repo and install NHentai, issue may exist for other extensions that use flaresolverr but I haven't checked
![2_install_extension](https://github.com/Suwayomi/Suwayomi-Server/assets/159391018/4eb1794c-6413-41e6-acec-be3b2f040135)
3. Click on NHentai to browse, wait for flaresolverr to finish
![3_flaresolverr_done](https://github.com/Suwayomi/Suwayomi-Server/assets/159391018/a8788742-76ac-47bd-a1e9-2f770a95af2b)
4. Go back to "Browse" page, refresh. Local source is now missing and server throws an error
![4_refresh_browse](https://github.com/Suwayomi/Suwayomi-Server/assets/159391018/6d77fce0-c349-4cdf-a80c-b5c49c07dbb6)
5. Error log from server when loading "Browse" page
[5_error_log.txt](https://github.com/Suwayomi/Suwayomi-Server/files/14202906/5_error_log.txt)

### Expected behavior
Browsing other sources should not remove the local source from the list of available sources.

### Actual behavior
See steps 4 and 5 above.

## Other details
Tried to reproduce this with a few other extensions and couldn't get it to happen, might only occur with extensions that use flaresolverr.

**Comment by Syer10** [comment]
Likely related to deregistering all sources after a new UA was sent to us. I'll take a look into fixing that when I can

**Comment by Syer10** [comment]
Fixed in the latest build 👍
