### ISSUE TITLE
[Feature Request] Komikku support

### ISSUE THREAD

**Issue by airi019** [AriaMoradi/Tachidesk#871]
## What feature should be added to Suwayomi?
make it work with this https://codeberg.org/valos/Komikku/

##  Why/Project's Benefit/Existing Problem
non-trash(java) desktop manga reader for linux.

**Comment by Robonau** [comment]
you should be asking them to support suwayomi-server no?

**Comment by Syer10** [comment]
Looks like they did
https://codeberg.org/valos/Komikku/issues/686

**Comment by airi019** [comment]
should I close the issue then?
I though maybe you guys could write a pull request

**Comment by Syer10** [comment]
I'm not familiar with python enough to write a extension for another client.

**Comment by airi019** [comment]
I'll close then.
Sorry for trouble.

**Comment by Robonau** [comment]
> I'm not familiar with python enough to write a extension for another client.

i'm also not to farmiliar with python but it seems like its just implementing the abstract methods from the  server class from [file](https://codeberg.org/valos/Komikku/src/branch/main/komikku/servers/__init__.py) that fetch the data in some way (using the api in suwayomi's case), idk about custom urls tho
