### ISSUE TITLE
[Bug] Wrong page order after download chapter(Manjaro 23.1.3)

### ISSUE THREAD

**Issue by ProjectKTC** [AriaMoradi/Tachidesk#879]
## Device information
- Suwayomi-Server version: v0.7.0 revision r1197
- Server Operating System: Manjaro Linux 23.1.3
- Server Desktop Environment: KDE Plasma 5.27.10
- Server JVM version: OpenJDK build 21+35 64bit
- Client Operating System: Manjaro Linux 23.1.3
- Client Web Browser: Firefox 122.0 64 bit

## Steps to reproduce
1. Install Suwayomi-Server(Tachidesk-server)
2. Install extension mangakatana from keiyoushi.github.io (or any other extension)
3. Add any manga/webtoon to your library
4. Select chapters to download
5. After download open it in tachidesk

### Expected behavior
Load first image(001.jpeg) as page 1 of that chapter and going on with correct order

### Actual behavior
Always as first page is loaded page number 015(image loaded is 015.jpeg)(tachidesk show page 1) and also other page order is messed up

## Other details
Bug don't occur if you read it without download or if you download it after start reading that chapter online.
Bug don't occur on Windows 10 22h2(latest update)
Example:
![Manjaro local files](https://github.com/Suwayomi/Suwayomi-Server/assets/49903836/55f65e49-5af5-4606-9abb-e7e9dc3c4ae3)
![Manjaro page 1](https://github.com/Suwayomi/Suwayomi-Server/assets/49903836/a22c2ad1-8d9c-4774-9f4c-b84f5556317b)
![Manjaro page 21](https://github.com/Suwayomi/Suwayomi-Server/assets/49903836/bc857387-998a-4c46-bae8-0cd7a9ddc35f)

**Comment by Syer10** [comment]
This was an issue with the stable build of Suwayomi, its been fixed for a long time now, we just need to get a release out. Feel free to use the preview version of Suwayomi https://github.com/Suwayomi/Suwayomi-Server-preview/releases
