### ISSUE TITLE
[Feature Request] Multi-threaded downloads

### ISSUE THREAD

**Issue by korewaChino** [AriaMoradi/Tachidesk#899]
## What feature should be added to Suwayomi?
Allow Suwayomi to download multiple chapters at once instead of one at a time

##  Why/Project's Benefit/Existing Problem
This makes downloading multiple chapters faster, as you can download multiple chapters at once instead of going through each one.

Implementation-wise, you don't need to download the entire queue at once, but can have a limit for how much it could download at once

**Comment by Syer10** [comment]
This has been considered before and we decided not to. Multi-threaded download is a easy path to get banned from the website. Because of this, we allow multi-threaded by source downloads, but not multi-threaded by chapters.
