### ISSUE TITLE
[Bug] Help install in Linux Mint

### ISSUE THREAD

**Issue by vyrus027** [AriaMoradi/Tachidesk#902]
I have been trying to install Suwayomi in Linux Mint. I follow the guide on the main page but the terminal is giving me this
"Cannot add PPA: ''No supported PPA of this name was found.''

Is there any updated guide on how to install suwayomi. Thanks.

**Comment by Robonau** [comment]
the ppa might still be tachidesk instead of suwayomi, u can try replacing "suwayomi" with "tachidesk"
or u can just download and install the .deb if that's easier

**Comment by Robonau** [comment]
@vyrus027 what did you end up doing, was it the ppa change or just the .deb
