### ISSUE TITLE
[Bug] Can't mark previous as read if selected chapter is larger than 100

### ISSUE THREAD

**Issue by boydaihungst** [AriaMoradi/Tachidesk#909]
## Device information
- Suwayomi-Server version: v1.0.0-r1498-debian-all
- Server Operating System: Ubuntu server 23.04 x86_64
- Server Desktop Environment: N/A
- Server JVM version: OpenJDK 8u392
- Client Operating System: EndeavourOS Linux x86_64
- Client Web Browser: Firefox 124.0.1

## Steps to reproduce
1. Add new manga, with more than 100 chapters, from any source to library
2. Open the manga
3. Click the `Options` button on the right side of latest chapter
4. After menu context is shown up, click `Mark previous as read`
5. An error dialog with text `Could not mark chapters as read` is shown up.

### Expected behavior
All chapters behind the selected chapter should be marked as read. 

### Actual behavior
Currently, it only works if the selected chapter is less than 100. Tested in localhost.

## Other details
Here is the GraphQL queries and responses.
[less_than_100_chapter_request.json](https://github.com/Suwayomi/Suwayomi-Server/files/14742529/less_than_100_chapter_request.json)
[less_than_100_chapter_response.json](https://github.com/Suwayomi/Suwayomi-Server/files/14742530/less_than_100_chapter_res.json)
[more_than_100_chapter_request.json](https://github.com/Suwayomi/Suwayomi-Server/files/14742531/more_than_100_chapter_request.json)
[more_than_100_chapter_response.json](https://github.com/Suwayomi/Suwayomi-Server/files/14742532/more_than_100_chapter_res.json)

Log said that I don't have permission, but I do.
![image](https://github.com/Suwayomi/Suwayomi-Server/assets/38396158/7dfe6e82-7e19-41b7-ac66-8dfb015039e4)

**Comment by Robonau** [comment]
i can't reproduce the issue
tested setting 261 chapters read and unread, worked fine
have you done anything special/non-standard (limiting memory usage, behind a reverse proxy, etc)

**Comment by boydaihungst** [comment]
No, I didn't run it through nginx. I use this url `http://192.168.1.100:4567/`. Also, my server has UFW firewall, but allow all incoming ports from my client IP: `Anywhere  ALLOW IN    192.168.1.4`, outgoing is allowed by default (didn't use any VPN). Tested on both Chrome and Firefox still has this problem. 
As far as I know, there isn't any memory limited by default (I don't touch anything related to memory, other process can reach 2-3 GB without any issue).
I follow this guide to install suwayomi-server #896. Even openjdk-8-jre is new installed.

**Comment by boydaihungst** [comment]
Feel free to close this issue if you still can't reproduce it. 👍

**Comment by taos15** [comment]
I couldn't reproduce either, my PR that update the local read database to match the tracker make requests to set chapters to read/unread, and it is working find with martial peak (over 3k chapters).
