### ISSUE TITLE
[Feature Request] Allow CORS

### ISSUE THREAD

**Issue by taos15** [AriaMoradi/Tachidesk#929]
## What feature should be added to Suwayomi?
**As an User** I want to be able to pass a list of domain to add to the server CORS, so I can make request from other clients using reverse proxy.

The list can be a field array in the config file, or and Enviropment variable. Both if posible. 

[Javalin CORS implementation](https://javalin.io/plugins/cors#getting-started)

##  Why/Project's Benefit/Existing Problem
By allowing the user to pass thier allowed domains, the user can host the webui in different domains without having problems to connect to the server.

**Comment by Robonau** [comment]
the CORS settings are already 100% open
https://github.com/Suwayomi/Suwayomi-Server/blob/db5c5ed5344416b1701db1d046861fe3776c5317/server/src/main/kotlin/suwayomi/tachidesk/server/JavalinSetup.kt#L56

https://github.com/Suwayomi/Suwayomi-Server/issues/337

its only an issue i ran in to on nginx
no issues on traefik

**Comment by Syer10** [comment]
Any CORS settings is just going to get overwritten by your reverse proxy anyway

**Comment by Robonau** [comment]
> Any CORS settings is just going to get overwritten by your reverse proxy anyway

nah, not setting any in nginx should use the source, it just doesn't with suwayomi fsr

**Comment by taos15** [comment]
The problem seen to be in the client and reverse proxy implementation, reference [WebUI Pr 721](https://github.com/Suwayomi/Suwayomi-WebUI/pull/721). By default one cannot s nd credentials (cookies, jwt), when using wildcard domain. If using reverse proxy, one need to make sure the proxy and the policy control for the subdomain, and the client needs to send the fetch request with the `credentials: include` field. Closing issues.
