### ISSUE TITLE
[Bug] Auto Download not working for specific extension (that keep the total chapter same)

### ISSUE THREAD

**Issue by krakerz** [AriaMoradi/Tachidesk#949]
## Device information
- Suwayomi-Server version: v1.0.0 with Build Time Fri, 23 Feb 2024 18:36:26 GMT
- Server Operating System: Docker from github

## Steps to reproduce
1. Go get working manga plus extension (currently i only know this extension that did this)
2. Grab one of manga from there, and set the server to auto download
3. Wait until new chapter released (mostly weekly tho)

### Expected behavior
new chapter auto downloaded

### Actual behavior
no new chapter auto downloaded, this probably due the site host keep the chapter number consistent (in this case 6) so suwayomi didnt detect any new chapter because of that, its possible fix is, suwayomi detect the state of each chapter (downloaded or not, if not, grab it for download)

## Other details
this host keep 6 chapter (3 latest and 3 first chapter only) so the total chapter number still constant 6, while other host (normal ones) always increase 1 chapter count in their chapter list

**Comment by schroda** [comment]
this is fixed in the preview version
