### ISSUE TITLE
Add button "Download Unread Chapters"

### ISSUE THREAD

**Issue by dpkass** [AriaMoradi/Tachidesk#952]
## What feature should be added to Suwayomi?
Add a button at the top of the Manga View, to download unread chapters.

##  Why
Improve QoL of Users

I think this is fairly self-explanatory, but I'm happy to answer any other questions :)

**Comment by Robonau** [comment]
1. this is a client issue not a server issue
2. you can already do this with a couple clicks in both webui and vui

WEBUI:
- in library
- click `select all` (top right)
- click `{number} MANGA` in the bottom right
- hover `download selected`
- click `all`

VUI:
- in library
- click `select all`
- click `download unread`
- wait for confirmation box telling you how many chapters you are about to add to the download queue
- click `Downlaod`
