### ISSUE TITLE
[Feature Request] Support merged entries from SY

### ISSUE THREAD

**Issue by kana-shii** [AriaMoradi/Tachidesk#965]
## What feature should be added to Suwayomi?
Add a way to merge entries and support already merged entries from TachiyomiSY backups
##  Why/Project's Benefit/Existing Problem
Right now, merged entries gives out absolutely nothing and creates something in the migrate section.
![image](https://github.com/Suwayomi/Suwayomi-Server/assets/79055104/461bc83c-a9e9-4bed-8248-324320e85d17)
![image](https://github.com/Suwayomi/Suwayomi-Server/assets/79055104/09d9d748-96d6-4e23-b28c-5806b08790f0)

**Comment by Syer10** [comment]
SY merged entries will likely never be supported unless we implement our own merge system, which I doubt. SY only has merge because EH had a broken version and some people wanted to try to make a working version. I don't see it being added here.
