### ISSUE TITLE
Add contextual menu in manga search results

### ISSUE THREAD

**Issue by Gron21** [AriaMoradi/Tachidesk#967]
Contextual menu for dowload before access manga,

When search from sources -> result a manga list -> in that screen, right-click on a manga open a contextual menu with download option.

It can help for less clicks to get manga... if you know it already or before...

**Comment by Syer10** [comment]
1. This is a client request, not a server request. If you are requesting this for WebUI, go to https://github.com/Suwayomi/Suwayomi-WebUI
2. Please use the formatting required, issues not using the formatting will be closed.
