### ISSUE TITLE
[Feature Request] Customizable Cache Location

### ISSUE THREAD

**Issue by eristocrates** [AriaMoradi/Tachidesk#971]
## What feature should be added to Suwayomi?
I'd like a feature to select Cache location. Currently it defaults to my OS drive which unfortunately is always strapped for space. I have plenty of other drives already to address this, and I would like to store Suwayomi's cache there instead

##  Why/Project's Benefit/Existing Problem
With a large enough collection, the program becomes near unusable. If i don't manually clear the cache regularly, upwards of 15GB & beyond from my OS drive is taken up just by Suwayomi alone.

**Comment by Robonau** [comment]
you can already change the root folder
(youl want to manually copy everything from the current location to the new location first)

**Comment by Syer10** [comment]
And you can change the temporary files directory using this java run option https://stackoverflow.com/questions/1924136/environment-variable-to-control-java-io-tmpdir

**Comment by eristocrates** [comment]
I suppose i missed the connection between the root directory and the cache. Thank you very much for the support.
