### ISSUE TITLE
i think the new update is not compatible with some extensions

### ISSUE THREAD

**Issue by aymanharrawi** [AriaMoradi/Tachidesk#974]
i think the new update is not compatible with some extensions , the extension i use "mangalek" arabic extention was working on the old version but after update its just giving http 520 error for every thing its not even trying to use flaresolverr and the website working perfectly on the browser fast, but on suwayomi just giving http 520 error instantly without even trying to reload

**Comment by Robonau** [comment]
just tested mangalek on v1.1.1-r1535 with flaresolverr setup and it works fine
