### ISSUE TITLE
[Bug] (DISCLAIMER : not really a bug, just not really tech savvy and don't know how to update Suwayomi)

### ISSUE THREAD

**Issue by popopiko** [AriaMoradi/Tachidesk#975]
As the title says, I just don't know how to update Suwayomi. I don't really want to do anything destructive like deleting the old version just in case I lose my whole library. Again, I know this is not a bug, just don't really know what to class this as.

Sorry.

**Comment by Robonau** [comment]
if u installed using the msi then you can just install the new msi

if you are using the zip you can safely delete the old version and replace it with the new
the data is stored in the root/[data directory](https://github.com/Suwayomi/Suwayomi-Server/wiki/The-Data-Directory) for the program not in the program files (unless you manually set it to store data there)
you can make a backup in settings just encase if you are still worried

**Comment by popopiko** [comment]
> if u installed using the msi then you can just install the new msi
> 
> if you are using the zip you can safely delete the old version and replace it with the new the data is stored in the root/[data directory](https://github.com/Suwayomi/Suwayomi-Server/wiki/The-Data-Directory) for the program not in the program files (unless you manually set it to store data there) you can make a backup in settings just encase if you are still worried

I do have a backup, but I'm scared its not up to date. I had recently added new manhwas to my library, about a week ago. I got on Suwayomi today to read some new chapters, and saw a huge error message that I'm assuming is from not having the latest version : 

(error in question)

Error loading categories: {
    "name": "CombinedError",
    "graphQLErrors": [],
    "networkError": {},
    "response": {}
}

That's why I was trying to update it, and I guess I just got really scared of losing my library (there's easily 100+ manhwas/manhuas/mangas, and it'd be impossible for me to remember all the titles).

I downloaded the zip, so if it is ok to delete the old version, I'll do that. Just to be sure though, the root/datadirectory isn't in any of the actual Suwayomi files right? It's stored in some backlog on my computer?

PS - I've never seen an msi download before, what is it exactly? Is it like a client or something?

**Comment by Robonau** [comment]
There are auto backups in the root/data directory, i don't remember how frequent they are by default though

The error message shouldn't be anything to worry about, in fact i'm pretty sure its just a placeholder error that VUI throws when it cant connect to the server, I've never seen anyone other than me (in development) get it tho

Unless you manually set the root directory to somewhere else then the data directory will been in the place this [link](https://github.com/Suwayomi/Suwayomi-Server/wiki/The-Data-Directory) says is it will be

The .msi is a windows installer
so you don't have to deal with the zip or any of the program files manually
it is generally recommended to use the .msi over the .zip for end users.

**Comment by popopiko** [comment]
Thank you so much for clarifying things Robonau, I really appreciate your patience in walking me through everything. Have a nice day.
