### ISSUE TITLE
[Bug] Basic authentication bug

### ISSUE THREAD

**Issue by popopiko** [AriaMoradi/Tachidesk#976]
Heyo,

Thought this was a problem with my version, but turns out it wasn't _(Had made a post inquiring about how to update prior to this one, thank you once again **Robonau** for the help ❤️ )_. Error still persists even after update. Best guess is that something broke around the time of the update, since everything was working fine before. This has to be taken with a grain of salt, since the last time I had used it was around a week ago. Could be a case of correlation-causation fallacy on my part.

The fix though is pretty simple, just disable the basic-authentication. While it isn't a huge problem, could be a cause for concern for those who want to keep their libraries private due to X or Y reason. If it is just an isolated issue on my end, I don't really know what changed to cause this. If it isn't, and other people are experiencing it too, please make sure to respond to this post. I've searched around and it seems I'm the only one who encountered such an issue, would be great to get some reassurance that I'm not the only one.

Thanks in advance,

_popopiko_

---

**## Device information**
- Suwayomi-Server version: Suwayomi-Server-v1.1.1-r1535-windows-x64
- Server Operating System: Windows 10 Home v.22H2
- Server Desktop Environment: N/A
- Server JVM version: Java version "21.0.3" 2024-04-16 LTS /
Java(TM) SE Runtime Environment (build 21.0.3+7-LTS-152) /
Java HotSpot(TM) 64-Bit Server VM (build 21.0.3+7-LTS-152, mixed mode, sharing)
- Client Operating System: Windows 10 Home v.22H2
- Client Web Browser: Opera One (version: 110.0.5130.82)

**## Steps to reproduce**
1. Enable "Basic Authentication"
2. Launch it (Browser or Electron has the same result for me)

**### Expected behavior**
There should be a pop up inquiring the username and password inserted in "Basic Authentication", which you then fill in to access your library.

**### Actual behavior**
This error shows up on all tabs : { "name": "CombinedError", "graphQLErrors": [], "networkError": {}, "response": {} }

**## Other details**
For the library, there is an additional part of the error message -> Error loading categories : { "name": "CombinedError", "graphQLErrors": [], "networkError": {}, "response": {} }

**Comment by Robonau** [comment]
the errors are a VUI thing they are just a could not connect to the server, as i mentioned in the previous issue

this issue shouldn't happen on either of the two ways to run VUI
though you should be able to force the Authentication popup by going to /api/graphql

it should then save the login for a session

given you didn't even mention you were using VUI i'm guessing you are doing something that is causing the issue and didn't think to mention it

**Comment by popopiko** [comment]
> the errors are a VUI thing they are just a could not connect to the server, as i mentioned in the previous issue
> 
> this issue shouldn't happen on either of the two ways to run VUI though you should be able to force the Authentication popup by going to /api/graphql
> 
> it should then save the login for a session
> 
> given you didn't even mention you were using VUI i'm guessing you are doing something that is causing the issue and didn't think to mention it

I am using VUI actually. Wasn't aware this issue existed. Thank you once again Robonau.
