### ISSUE TITLE
[Feature Request] Grouping notifications for new chapters in updates tab

### ISSUE THREAD

**Issue by zjDrummond** [AriaMoradi/Tachidesk#981]
---

## What feature should be added to Suwayomi?
The updates tab needs the option (preferably a default one) to group update notifications per title. "5 new chapters for _Chainsaw Man"_ "12 new chapters for _"My Life as a Slime"_ or something like that. 

##  Why/Project's Benefit/Existing Problem
The updates tab can easily become cluttered if a user has many items in their library. It is not uncommon for many chapters of a single title to be released at once in a batch instead of one per week or so. Granted this is more a problem for webtoons than with manga, but it would still be nice to have. 

Thanks for the consideration.

**Comment by Robonau** [comment]
this is a client issue
remake this issue in the repo for whatever client you are using
