### ISSUE TITLE
[Bug] Unable to load data java.io.IOException: Failed to connect to localhost/0:0:0:0:0:0:0:1:8191

### ISSUE THREAD

**Issue by popopiko** [AriaMoradi/Tachidesk#982]
Heyo,

As you can see, the title itself is the name of the error message. This is concerning the MangaGeko extension specifically, as it is the only extension that I've used with that error.

My best guess is that is has something to do with CloudFlare authentication blocking access, but there are 2 reasons why I think this is  the result of a bug : 

- FlareSolver is enabled,
- I had 0 issues until about 5 minutes ago.

And I'm certain it looks really dumb to some of the people who might be reading this, since I could just migrate to another extension.

The reason I'm so pressed about it is because MangaGeko loads really fast for me, it's consistent, and it has a huge collection. A vast majority of mangas/manhwas/manhuas that I read is using the MangaGeko extension.

For me, it's been the most consistently updating, fastest loading extension out of all the ones that I use currently, and it would just be a shame to lose it over a bug like this (assuming it is a bug).

Thanks in advance.

_popopiko_

---

## Device information

- Suwayomi-Server version: Suwayomi-Server-v1.1.1-r1535-windows-x64
- Server Operating System: Windows 10 Home v.22H2
- Server Desktop Environment: N/A
- Server JVM version: Java version "21.0.3" 2024-04-16 LTS / Java(TM) SE Runtime Environment (build 21.0.3+7-LTS-152) / Java HotSpot(TM) 64-Bit Server VM (build 21.0.3+7-LTS-152, mixed mode, sharing)
- Client Operating System: Windows 10 Home v.22H2
- Client Web Browser: Opera One (version: 110.0.5130.82)

## Steps to reproduce
1. Open up a manga/manhwa/manhua using the MangaGeko extension

### Expected behavior
Manga/manhwa/manhua loads like normal.

### Actual behavior
This error shows up : Unable to load data
java.io.IOException: Failed to connect to localhost/0:0:0:0:0:0:0:1:8191

## Other details
The MangaGeko extension was working just fine a couple minutes ago. Thought it was weird so posted it just in case something was bugged.

**Comment by Robonau** [comment]
im guessing its an extension issue not a suwayomi issue

test if it works in mihon
if it doesn't work then its and extension issue and this issue should be made in whatever repo you are using to get your extensions, not here

if it is suwayomi specific then say so

**Comment by popopiko** [comment]
That's going to be a little difficult. I unfortunately don't have an android, so I won't be able to check using Mihon. Is there maybe a way to get it on my computer without using an emulator?

**Comment by Robonau** [comment]
it fails in mihon

**Comment by popopiko** [comment]
I see, so it's an extension issue then. Is it possible it's directly related to the repo I'm using? Maybe an update got pushed out for the extension that I wasn't aware of?

**Comment by popopiko** [comment]
Never mind, you already suggested that as being a possible source of the issue. This is the repo I'm using for all my extensions : 
https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json

Is this also the one you're using?

**Comment by Robonau** [comment]
the website just changed
it will probably be a while before its fixed (if it is at all)
and no one has reported it as broken yet, so i doubt any devs are even aware its broken

either way you can close this issue as its not a suwayomi issue

**Comment by popopiko** [comment]
I see. Thank you once again Robonau. Helpful as always.

**Comment by popopiko** [comment]
Wait, I just checked on the wayback machine, and it seems the URL is still the same? Plus, if the website changed, does it make sense that I can still click **Open Site** and it still brings me to the right site?

![image_2024-06-27_174706904](https://github.com/Suwayomi/Suwayomi-Server/assets/173263233/496d1de4-4bc6-4885-aa4e-32de9a84284c)

**Comment by Robonau** [comment]
url changes aren't the only thing that can break an extension

**Comment by popopiko** [comment]
> url changes aren't the only thing that can break an extension

I see. I'll close it again then. Thanks for the clarification.

**Comment by schroda** [comment]
you might have flaresolverr enabled in suwayomi, but have you checked that it's actually running? because suwayomi fails to connect to it

**Comment by Robonau** [comment]
yea, i just checked it on my suwayomi and it worked fine

**Comment by popopiko** [comment]
> you might have flaresolverr enabled in suwayomi, but have you checked that it's actually running? because suwayomi fails to connect to it

how do I check?

**Comment by schroda** [comment]
open the flaresolverr url in the browser and you'll get a screen with a message like this
```json
{
    "msg": "FlareSolverr is ready!",
    "version": "3.3.21",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
}
```
