### ISSUE TITLE
[Feature Request] Notification system for new chapters

### ISSUE THREAD

**Issue by amau05** [AriaMoradi/Tachidesk#986]
## What feature should be added to Suwayomi?

A way to get a notification on our phone when Suwayomi has downloaded a new chapter on a platform like Gotify some people also like it in things like Discord, Telegram, ...

##  Why/Project's Benefit/Existing Problem

It will let us know there is a new chapter available to read. I already use it on things like Sonarr, Radarr, ... It is really useful, especially if we are too eager to read the next chapter on some webtoon/manga/... .

What do you think?

https://github.com/gotify/server/

**Comment by Robonau** [comment]
all the needed data is accessible via the suwayomi gql api
it shouldn't be too difficult to write an external script to do what you want

**Comment by Syer10** [comment]
I would suggest going the script route, it wouldn't be difficult to use a graphql subscription for this.

**Comment by sfai05** [comment]
@amau05 I created https://github.com/sfai05/tachidesk-notifier. It fetch the latest chapter from suwayomi gql api and send notificaition to your telegram channel.
