### ISSUE TITLE
[Feature Request] Ability to refresh all local source manga

### ISSUE THREAD

**Issue by schroda** [AriaMoradi/Tachidesk#993]
## What feature should be added to Suwayomi?
A graphql mutation to be able to refresh all local source manga

##  Why/Project's Benefit/Existing Problem
see https://github.com/Suwayomi/Suwayomi-WebUI/issues/779

**Comment by Robonau** [comment]
why make something specific to local source and not something more generic like a to bulk refresh by manga id
so it can be done by selection in library

**Comment by schroda** [comment]
well tbh, I don't really see the need of this ticket or being able to batch update specific manga

didn't think about this before creating this ticket, but as I've wrote in the webUI ticket afterwards, if someone has the same problem they should just add all the local source manga into the same category and update only this category

so I'll just close this one
